using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Devinno.Skia.Utils;
using Devinno.Skia.Controls;
using Devinno.Skia.Containers;
using Devinno.Skia.Design;

namespace SampleForm.Pages
{
    partial class PageContainer
    {
        #region declare
        private DvScrollablePanel scrpnl;
        private DvTableLayoutPanel tbl;
        private DvPanel pnl;
        private DvBorderPanel borderpnl;
        private DvBoxPanel boxpnl;
        private DvGroupBox grpbox;
        private DvTabControl tqb;
        private DvSubPage tpTab1;
        private DvButton btnItem1;
        private DvSubPage tpTab2;
        private DvButton btnItem2;
        private DvButton btnItem3;
        private DvSubPage tpTab3;
        private DvButton btnItem4;
        private DvButton btnItem5;
        private DvButton btnItem6;
        private DvTableLayoutPanel dvTableLayoutPanel1;
        private DvLabel box1;
        private DvLabel box2;
        private DvLabel box3;
        private DvLabel box4;
        private DvLabel box5;
        private DvLabel box6;
        private DvLabel box7;
        private DvLabel box8;
        private DvLabel box9;
        private DvLabel box10;
        private DvLabel box11;
        private DvLabel box12;
        private DvLabel box13;
        private DvLabel box14;
        private DvLabel box15;
        private DvLabel box16;
        private DvLabel box17;
        private DvLabel box18;
        #endregion

        public void InitializeComponent()
        {
            #region base
            UseMasterPage = true;
            BackgroundDraw = false;
            BackColor = null;
            BackgroundImage = null;
            AnimationType = null;
            Text = "Container";
            IconString = "";
            #endregion

            #region new
            scrpnl = new DvScrollablePanel { Name = nameof(scrpnl) };
            tbl = new DvTableLayoutPanel { Name = nameof(tbl) };
            pnl = new DvPanel { Name = nameof(pnl) };
            borderpnl = new DvBorderPanel { Name = nameof(borderpnl) };
            boxpnl = new DvBoxPanel { Name = nameof(boxpnl) };
            grpbox = new DvGroupBox { Name = nameof(grpbox) };
            tqb = new DvTabControl { Name = nameof(tqb) };
            tpTab1 = new DvSubPage { Name = nameof(tpTab1) };
            btnItem1 = new DvButton { Name = nameof(btnItem1) };
            tpTab2 = new DvSubPage { Name = nameof(tpTab2) };
            btnItem2 = new DvButton { Name = nameof(btnItem2) };
            btnItem3 = new DvButton { Name = nameof(btnItem3) };
            tpTab3 = new DvSubPage { Name = nameof(tpTab3) };
            btnItem4 = new DvButton { Name = nameof(btnItem4) };
            btnItem5 = new DvButton { Name = nameof(btnItem5) };
            btnItem6 = new DvButton { Name = nameof(btnItem6) };
            dvTableLayoutPanel1 = new DvTableLayoutPanel { Name = nameof(dvTableLayoutPanel1) };
            box1 = new DvLabel { Name = nameof(box1) };
            box2 = new DvLabel { Name = nameof(box2) };
            box3 = new DvLabel { Name = nameof(box3) };
            box4 = new DvLabel { Name = nameof(box4) };
            box5 = new DvLabel { Name = nameof(box5) };
            box6 = new DvLabel { Name = nameof(box6) };
            box7 = new DvLabel { Name = nameof(box7) };
            box8 = new DvLabel { Name = nameof(box8) };
            box9 = new DvLabel { Name = nameof(box9) };
            box10 = new DvLabel { Name = nameof(box10) };
            box11 = new DvLabel { Name = nameof(box11) };
            box12 = new DvLabel { Name = nameof(box12) };
            box13 = new DvLabel { Name = nameof(box13) };
            box14 = new DvLabel { Name = nameof(box14) };
            box15 = new DvLabel { Name = nameof(box15) };
            box16 = new DvLabel { Name = nameof(box16) };
            box17 = new DvLabel { Name = nameof(box17) };
            box18 = new DvLabel { Name = nameof(box18) };
            #endregion

            #region controls
            #region scrpnl
            scrpnl.TouchMode = true;
            scrpnl.Name = "scrpnl";
            scrpnl.X = 10F;
            scrpnl.Y = 60F;
            scrpnl.Width = 780F;
            scrpnl.Height = 410F;
            scrpnl.Visible = true;
            scrpnl.Enabled = true;
            scrpnl.Fill = true;
            scrpnl.Margin = new Padding(10, 60, 10, 10);
            #endregion
            #region tbl
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 40F));
            tbl.Name = "tbl";
            tbl.X = 10F;
            tbl.Y = 10F;
            tbl.Width = 750F;
            tbl.Height = 900F;
            tbl.Visible = true;
            tbl.Enabled = true;
            tbl.Fill = false;
            tbl.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region pnl
            pnl.ForeColor = null;
            pnl.PanelColor = null;
            pnl.DrawTitle = true;
            pnl.TitleHeight = 30;
            pnl.IconString = "";
            pnl.IconSize = 12F;
            pnl.IconGap = 5F;
            pnl.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            pnl.Text = "Panel";
            pnl.TextPadding = new Padding(0, 0, 0, 0);
            pnl.FontName = "NanumGothic";
            pnl.FontSize = 12F;
            pnl.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            pnl.Name = "pnl";
            pnl.X = 3F;
            pnl.Y = 3F;
            pnl.Width = 181.5F;
            pnl.Height = 174F;
            pnl.Visible = true;
            pnl.Enabled = true;
            pnl.Fill = false;
            pnl.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region borderpnl
            borderpnl.ForeColor = null;
            borderpnl.BorderColor = null;
            borderpnl.TitleHeight = 30;
            borderpnl.DrawTitle = true;
            borderpnl.BorderWidth = 6F;
            borderpnl.IconString = "";
            borderpnl.IconSize = 12F;
            borderpnl.IconGap = 5F;
            borderpnl.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            borderpnl.Text = "Border Panel";
            borderpnl.TextPadding = new Padding(0, 0, 0, 0);
            borderpnl.FontName = "NanumGothic";
            borderpnl.FontSize = 12F;
            borderpnl.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            borderpnl.Name = "borderpnl";
            borderpnl.X = 190.5F;
            borderpnl.Y = 3F;
            borderpnl.Width = 181.5F;
            borderpnl.Height = 174F;
            borderpnl.Visible = true;
            borderpnl.Enabled = true;
            borderpnl.Fill = false;
            borderpnl.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region boxpnl
            boxpnl.ForeColor = null;
            boxpnl.PanelColor = null;
            boxpnl.Corner = null;
            boxpnl.Round = null;
            boxpnl.TitleHeight = 30;
            boxpnl.IconString = "";
            boxpnl.IconSize = 12F;
            boxpnl.IconGap = 5F;
            boxpnl.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            boxpnl.Text = "Box Panel";
            boxpnl.TextPadding = new Padding(0, 0, 0, 0);
            boxpnl.FontName = "NanumGothic";
            boxpnl.FontSize = 12F;
            boxpnl.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            boxpnl.Name = "boxpnl";
            boxpnl.X = 378F;
            boxpnl.Y = 3F;
            boxpnl.Width = 181.5F;
            boxpnl.Height = 174F;
            boxpnl.Visible = true;
            boxpnl.Enabled = true;
            boxpnl.Fill = false;
            boxpnl.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region grpbox
            grpbox.ForeColor = null;
            grpbox.BorderColor = null;
            grpbox.BorderWidth = 1F;
            grpbox.IconString = "";
            grpbox.IconSize = 12F;
            grpbox.IconGap = 5F;
            grpbox.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            grpbox.Text = "Group Box";
            grpbox.TextPadding = new Padding(0, 0, 0, 0);
            grpbox.FontName = "NanumGothic";
            grpbox.FontSize = 12F;
            grpbox.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            grpbox.Name = "grpbox";
            grpbox.X = 565.5F;
            grpbox.Y = 3F;
            grpbox.Width = 181.5F;
            grpbox.Height = 174F;
            grpbox.Visible = true;
            grpbox.Enabled = true;
            grpbox.Fill = false;
            grpbox.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region tqb
            tqb.ForeColor = null;
            tqb.PageColor = null;
            tqb.TabBackColor = null;
            tqb.PointColor = null;
            tqb.Round = null;
            tqb.TabPosition = Devinno.Skia.Design.DvPosition.Left;
            tqb.TabSize = 120;
            tqb.TabPages.Add(tpTab1);
            tqb.TabPages.Add(tpTab2);
            tqb.TabPages.Add(tpTab3);
            tqb.FontName = "NanumGothic";
            tqb.FontSize = 12F;
            tqb.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            tqb.IconSize = 12F;
            tqb.IconGap = 5F;
            tqb.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            tqb.Name = "tqb";
            tqb.X = 3F;
            tqb.Y = 183F;
            tqb.Width = 744F;
            tqb.Height = 354F;
            tqb.Visible = true;
            tqb.Enabled = true;
            tqb.Fill = false;
            tqb.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region tpTab1
            tpTab1.Text = "Tab1";
            tpTab1.IconString = "fa-cube";
            tpTab1.Name = "tpTab1";
            tpTab1.X = 119F;
            tpTab1.Y = 0F;
            tpTab1.Width = 624F;
            tpTab1.Height = 354F;
            tpTab1.Visible = true;
            tpTab1.Enabled = true;
            tpTab1.Fill = false;
            tpTab1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnItem1
            btnItem1.IconString = "";
            btnItem1.IconSize = 12F;
            btnItem1.IconGap = 5F;
            btnItem1.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnItem1.Text = "Item1";
            btnItem1.TextPadding = new Padding(0, 0, 0, 0);
            btnItem1.FontName = "NanumGothic";
            btnItem1.FontSize = 12F;
            btnItem1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnItem1.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnItem1.BackgroundDraw = true;
            btnItem1.ButtonColor = null;
            btnItem1.ForeColor = null;
            btnItem1.BorderColor = null;
            btnItem1.Round = null;
            btnItem1.Gradient = true;
            btnItem1.Clickable = true;
            btnItem1.Name = "btnItem1";
            btnItem1.X = 10F;
            btnItem1.Y = 9.999985F;
            btnItem1.Width = 150F;
            btnItem1.Height = 30F;
            btnItem1.Visible = true;
            btnItem1.Enabled = true;
            btnItem1.Fill = false;
            btnItem1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region tpTab2
            tpTab2.Text = "Tab2";
            tpTab2.IconString = "fa-cubes";
            tpTab2.Name = "tpTab2";
            tpTab2.X = 119F;
            tpTab2.Y = 0F;
            tpTab2.Width = 624F;
            tpTab2.Height = 354F;
            tpTab2.Visible = true;
            tpTab2.Enabled = true;
            tpTab2.Fill = false;
            tpTab2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnItem2
            btnItem2.IconString = "";
            btnItem2.IconSize = 12F;
            btnItem2.IconGap = 5F;
            btnItem2.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnItem2.Text = "Item2";
            btnItem2.TextPadding = new Padding(0, 0, 0, 0);
            btnItem2.FontName = "NanumGothic";
            btnItem2.FontSize = 12F;
            btnItem2.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnItem2.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnItem2.BackgroundDraw = true;
            btnItem2.ButtonColor = null;
            btnItem2.ForeColor = null;
            btnItem2.BorderColor = null;
            btnItem2.Round = null;
            btnItem2.Gradient = true;
            btnItem2.Clickable = true;
            btnItem2.Name = "btnItem2";
            btnItem2.X = 10F;
            btnItem2.Y = 10F;
            btnItem2.Width = 150F;
            btnItem2.Height = 30F;
            btnItem2.Visible = true;
            btnItem2.Enabled = true;
            btnItem2.Fill = false;
            btnItem2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnItem3
            btnItem3.IconString = "";
            btnItem3.IconSize = 12F;
            btnItem3.IconGap = 5F;
            btnItem3.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnItem3.Text = "Item3";
            btnItem3.TextPadding = new Padding(0, 0, 0, 0);
            btnItem3.FontName = "NanumGothic";
            btnItem3.FontSize = 12F;
            btnItem3.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnItem3.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnItem3.BackgroundDraw = true;
            btnItem3.ButtonColor = null;
            btnItem3.ForeColor = null;
            btnItem3.BorderColor = null;
            btnItem3.Round = null;
            btnItem3.Gradient = true;
            btnItem3.Clickable = true;
            btnItem3.Name = "btnItem3";
            btnItem3.X = 10F;
            btnItem3.Y = 50F;
            btnItem3.Width = 150F;
            btnItem3.Height = 30F;
            btnItem3.Visible = true;
            btnItem3.Enabled = true;
            btnItem3.Fill = false;
            btnItem3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region tpTab3
            tpTab3.Text = "Tab3";
            tpTab3.IconString = "fa-layer-group";
            tpTab3.Name = "tpTab3";
            tpTab3.X = 119F;
            tpTab3.Y = 0F;
            tpTab3.Width = 624F;
            tpTab3.Height = 354F;
            tpTab3.Visible = true;
            tpTab3.Enabled = true;
            tpTab3.Fill = false;
            tpTab3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnItem4
            btnItem4.IconString = "";
            btnItem4.IconSize = 12F;
            btnItem4.IconGap = 5F;
            btnItem4.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnItem4.Text = "Item 4";
            btnItem4.TextPadding = new Padding(0, 0, 0, 0);
            btnItem4.FontName = "NanumGothic";
            btnItem4.FontSize = 12F;
            btnItem4.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnItem4.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnItem4.BackgroundDraw = true;
            btnItem4.ButtonColor = null;
            btnItem4.ForeColor = null;
            btnItem4.BorderColor = null;
            btnItem4.Round = null;
            btnItem4.Gradient = true;
            btnItem4.Clickable = true;
            btnItem4.Name = "btnItem4";
            btnItem4.X = 10F;
            btnItem4.Y = 9.999985F;
            btnItem4.Width = 150F;
            btnItem4.Height = 30F;
            btnItem4.Visible = true;
            btnItem4.Enabled = true;
            btnItem4.Fill = false;
            btnItem4.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnItem5
            btnItem5.IconString = "";
            btnItem5.IconSize = 12F;
            btnItem5.IconGap = 5F;
            btnItem5.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnItem5.Text = "Item 5";
            btnItem5.TextPadding = new Padding(0, 0, 0, 0);
            btnItem5.FontName = "NanumGothic";
            btnItem5.FontSize = 12F;
            btnItem5.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnItem5.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnItem5.BackgroundDraw = true;
            btnItem5.ButtonColor = null;
            btnItem5.ForeColor = null;
            btnItem5.BorderColor = null;
            btnItem5.Round = null;
            btnItem5.Gradient = true;
            btnItem5.Clickable = true;
            btnItem5.Name = "btnItem5";
            btnItem5.X = 10F;
            btnItem5.Y = 49.999985F;
            btnItem5.Width = 150F;
            btnItem5.Height = 30F;
            btnItem5.Visible = true;
            btnItem5.Enabled = true;
            btnItem5.Fill = false;
            btnItem5.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnItem6
            btnItem6.IconString = "";
            btnItem6.IconSize = 12F;
            btnItem6.IconGap = 5F;
            btnItem6.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnItem6.Text = "Item 6";
            btnItem6.TextPadding = new Padding(0, 0, 0, 0);
            btnItem6.FontName = "NanumGothic";
            btnItem6.FontSize = 12F;
            btnItem6.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnItem6.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnItem6.BackgroundDraw = true;
            btnItem6.ButtonColor = null;
            btnItem6.ForeColor = null;
            btnItem6.BorderColor = null;
            btnItem6.Round = null;
            btnItem6.Gradient = true;
            btnItem6.Clickable = true;
            btnItem6.Name = "btnItem6";
            btnItem6.X = 10F;
            btnItem6.Y = 89.999985F;
            btnItem6.Width = 150F;
            btnItem6.Height = 30F;
            btnItem6.Visible = true;
            btnItem6.Enabled = true;
            btnItem6.Fill = false;
            btnItem6.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region dvTableLayoutPanel1
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Name = "dvTableLayoutPanel1";
            dvTableLayoutPanel1.X = 0F;
            dvTableLayoutPanel1.Y = 540F;
            dvTableLayoutPanel1.Width = 750F;
            dvTableLayoutPanel1.Height = 360F;
            dvTableLayoutPanel1.Visible = true;
            dvTableLayoutPanel1.Enabled = true;
            dvTableLayoutPanel1.Fill = false;
            dvTableLayoutPanel1.Margin = new Padding(0, 0, 0, 0);
            #endregion
            #region box1
            box1.IconString = "";
            box1.IconSize = 12F;
            box1.IconGap = 5F;
            box1.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box1.Text = "Box 1";
            box1.TextPadding = new Padding(0, 0, 0, 0);
            box1.FontName = "NanumGothic";
            box1.FontSize = 12F;
            box1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box1.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box1.BackgroundDraw = true;
            box1.LabelColor = null;
            box1.ForeColor = null;
            box1.BorderColor = null;
            box1.Round = null;
            box1.Name = "box1";
            box1.X = 3F;
            box1.Y = 3F;
            box1.Width = 144F;
            box1.Height = 210F;
            box1.Visible = true;
            box1.Enabled = true;
            box1.Fill = false;
            box1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box2
            box2.IconString = "";
            box2.IconSize = 12F;
            box2.IconGap = 5F;
            box2.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box2.Text = "Box 2";
            box2.TextPadding = new Padding(0, 0, 0, 0);
            box2.FontName = "NanumGothic";
            box2.FontSize = 12F;
            box2.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box2.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box2.BackgroundDraw = true;
            box2.LabelColor = null;
            box2.ForeColor = null;
            box2.BorderColor = null;
            box2.Round = null;
            box2.Name = "box2";
            box2.X = 153F;
            box2.Y = 3F;
            box2.Width = 144F;
            box2.Height = 66F;
            box2.Visible = true;
            box2.Enabled = true;
            box2.Fill = false;
            box2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box3
            box3.IconString = "";
            box3.IconSize = 12F;
            box3.IconGap = 5F;
            box3.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box3.Text = "Box 3";
            box3.TextPadding = new Padding(0, 0, 0, 0);
            box3.FontName = "NanumGothic";
            box3.FontSize = 12F;
            box3.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box3.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box3.BackgroundDraw = true;
            box3.LabelColor = null;
            box3.ForeColor = null;
            box3.BorderColor = null;
            box3.Round = null;
            box3.Name = "box3";
            box3.X = 303F;
            box3.Y = 3F;
            box3.Width = 144F;
            box3.Height = 138F;
            box3.Visible = true;
            box3.Enabled = true;
            box3.Fill = false;
            box3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box4
            box4.IconString = "";
            box4.IconSize = 12F;
            box4.IconGap = 5F;
            box4.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box4.Text = "Box 4";
            box4.TextPadding = new Padding(0, 0, 0, 0);
            box4.FontName = "NanumGothic";
            box4.FontSize = 12F;
            box4.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box4.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box4.BackgroundDraw = true;
            box4.LabelColor = null;
            box4.ForeColor = null;
            box4.BorderColor = null;
            box4.Round = null;
            box4.Name = "box4";
            box4.X = 453F;
            box4.Y = 3F;
            box4.Width = 144F;
            box4.Height = 66F;
            box4.Visible = true;
            box4.Enabled = true;
            box4.Fill = false;
            box4.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box5
            box5.IconString = "";
            box5.IconSize = 12F;
            box5.IconGap = 5F;
            box5.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box5.Text = "Box 5";
            box5.TextPadding = new Padding(0, 0, 0, 0);
            box5.FontName = "NanumGothic";
            box5.FontSize = 12F;
            box5.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box5.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box5.BackgroundDraw = true;
            box5.LabelColor = null;
            box5.ForeColor = null;
            box5.BorderColor = null;
            box5.Round = null;
            box5.Name = "box5";
            box5.X = 603F;
            box5.Y = 3F;
            box5.Width = 144F;
            box5.Height = 66F;
            box5.Visible = true;
            box5.Enabled = true;
            box5.Fill = false;
            box5.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box6
            box6.IconString = "";
            box6.IconSize = 12F;
            box6.IconGap = 5F;
            box6.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box6.Text = "Box 6";
            box6.TextPadding = new Padding(0, 0, 0, 0);
            box6.FontName = "NanumGothic";
            box6.FontSize = 12F;
            box6.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box6.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box6.BackgroundDraw = true;
            box6.LabelColor = null;
            box6.ForeColor = null;
            box6.BorderColor = null;
            box6.Round = null;
            box6.Name = "box6";
            box6.X = 153F;
            box6.Y = 75F;
            box6.Width = 144F;
            box6.Height = 138F;
            box6.Visible = true;
            box6.Enabled = true;
            box6.Fill = false;
            box6.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box7
            box7.IconString = "";
            box7.IconSize = 12F;
            box7.IconGap = 5F;
            box7.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box7.Text = "Box 7";
            box7.TextPadding = new Padding(0, 0, 0, 0);
            box7.FontName = "NanumGothic";
            box7.FontSize = 12F;
            box7.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box7.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box7.BackgroundDraw = true;
            box7.LabelColor = null;
            box7.ForeColor = null;
            box7.BorderColor = null;
            box7.Round = null;
            box7.Name = "box7";
            box7.X = 453F;
            box7.Y = 75F;
            box7.Width = 144F;
            box7.Height = 66F;
            box7.Visible = true;
            box7.Enabled = true;
            box7.Fill = false;
            box7.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box8
            box8.IconString = "";
            box8.IconSize = 12F;
            box8.IconGap = 5F;
            box8.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box8.Text = "Box 8";
            box8.TextPadding = new Padding(0, 0, 0, 0);
            box8.FontName = "NanumGothic";
            box8.FontSize = 12F;
            box8.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box8.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box8.BackgroundDraw = true;
            box8.LabelColor = null;
            box8.ForeColor = null;
            box8.BorderColor = null;
            box8.Round = null;
            box8.Name = "box8";
            box8.X = 603F;
            box8.Y = 75F;
            box8.Width = 144F;
            box8.Height = 66F;
            box8.Visible = true;
            box8.Enabled = true;
            box8.Fill = false;
            box8.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box9
            box9.IconString = "";
            box9.IconSize = 12F;
            box9.IconGap = 5F;
            box9.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box9.Text = "Box 9";
            box9.TextPadding = new Padding(0, 0, 0, 0);
            box9.FontName = "NanumGothic";
            box9.FontSize = 12F;
            box9.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box9.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box9.BackgroundDraw = true;
            box9.LabelColor = null;
            box9.ForeColor = null;
            box9.BorderColor = null;
            box9.Round = null;
            box9.Name = "box9";
            box9.X = 303F;
            box9.Y = 147F;
            box9.Width = 294F;
            box9.Height = 66F;
            box9.Visible = true;
            box9.Enabled = true;
            box9.Fill = false;
            box9.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box10
            box10.IconString = "";
            box10.IconSize = 12F;
            box10.IconGap = 5F;
            box10.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box10.Text = "Box 10";
            box10.TextPadding = new Padding(0, 0, 0, 0);
            box10.FontName = "NanumGothic";
            box10.FontSize = 12F;
            box10.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box10.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box10.BackgroundDraw = true;
            box10.LabelColor = null;
            box10.ForeColor = null;
            box10.BorderColor = null;
            box10.Round = null;
            box10.Name = "box10";
            box10.X = 603F;
            box10.Y = 147F;
            box10.Width = 144F;
            box10.Height = 138F;
            box10.Visible = true;
            box10.Enabled = true;
            box10.Fill = false;
            box10.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box11
            box11.IconString = "";
            box11.IconSize = 12F;
            box11.IconGap = 5F;
            box11.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box11.Text = "Box 11";
            box11.TextPadding = new Padding(0, 0, 0, 0);
            box11.FontName = "NanumGothic";
            box11.FontSize = 12F;
            box11.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box11.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box11.BackgroundDraw = true;
            box11.LabelColor = null;
            box11.ForeColor = null;
            box11.BorderColor = null;
            box11.Round = null;
            box11.Name = "box11";
            box11.X = 3F;
            box11.Y = 219F;
            box11.Width = 144F;
            box11.Height = 66F;
            box11.Visible = true;
            box11.Enabled = true;
            box11.Fill = false;
            box11.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box12
            box12.IconString = "";
            box12.IconSize = 12F;
            box12.IconGap = 5F;
            box12.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box12.Text = "Box  12";
            box12.TextPadding = new Padding(0, 0, 0, 0);
            box12.FontName = "NanumGothic";
            box12.FontSize = 12F;
            box12.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box12.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box12.BackgroundDraw = true;
            box12.LabelColor = null;
            box12.ForeColor = null;
            box12.BorderColor = null;
            box12.Round = null;
            box12.Name = "box12";
            box12.X = 153F;
            box12.Y = 219F;
            box12.Width = 144F;
            box12.Height = 66F;
            box12.Visible = true;
            box12.Enabled = true;
            box12.Fill = false;
            box12.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box13
            box13.IconString = "";
            box13.IconSize = 12F;
            box13.IconGap = 5F;
            box13.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box13.Text = "Box 13";
            box13.TextPadding = new Padding(0, 0, 0, 0);
            box13.FontName = "NanumGothic";
            box13.FontSize = 12F;
            box13.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box13.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box13.BackgroundDraw = true;
            box13.LabelColor = null;
            box13.ForeColor = null;
            box13.BorderColor = null;
            box13.Round = null;
            box13.Name = "box13";
            box13.X = 303F;
            box13.Y = 219F;
            box13.Width = 144F;
            box13.Height = 66F;
            box13.Visible = true;
            box13.Enabled = true;
            box13.Fill = false;
            box13.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box14
            box14.IconString = "";
            box14.IconSize = 12F;
            box14.IconGap = 5F;
            box14.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box14.Text = "Box 14";
            box14.TextPadding = new Padding(0, 0, 0, 0);
            box14.FontName = "NanumGothic";
            box14.FontSize = 12F;
            box14.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box14.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box14.BackgroundDraw = true;
            box14.LabelColor = null;
            box14.ForeColor = null;
            box14.BorderColor = null;
            box14.Round = null;
            box14.Name = "box14";
            box14.X = 453F;
            box14.Y = 219F;
            box14.Width = 144F;
            box14.Height = 66F;
            box14.Visible = true;
            box14.Enabled = true;
            box14.Fill = false;
            box14.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box15
            box15.IconString = "";
            box15.IconSize = 12F;
            box15.IconGap = 5F;
            box15.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box15.Text = "Box 15";
            box15.TextPadding = new Padding(0, 0, 0, 0);
            box15.FontName = "NanumGothic";
            box15.FontSize = 12F;
            box15.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box15.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box15.BackgroundDraw = true;
            box15.LabelColor = null;
            box15.ForeColor = null;
            box15.BorderColor = null;
            box15.Round = null;
            box15.Name = "box15";
            box15.X = 3F;
            box15.Y = 291F;
            box15.Width = 144F;
            box15.Height = 66F;
            box15.Visible = true;
            box15.Enabled = true;
            box15.Fill = false;
            box15.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box16
            box16.IconString = "";
            box16.IconSize = 12F;
            box16.IconGap = 5F;
            box16.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box16.Text = "Box 16";
            box16.TextPadding = new Padding(0, 0, 0, 0);
            box16.FontName = "NanumGothic";
            box16.FontSize = 12F;
            box16.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box16.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box16.BackgroundDraw = true;
            box16.LabelColor = null;
            box16.ForeColor = null;
            box16.BorderColor = null;
            box16.Round = null;
            box16.Name = "box16";
            box16.X = 153F;
            box16.Y = 291F;
            box16.Width = 144F;
            box16.Height = 66F;
            box16.Visible = true;
            box16.Enabled = true;
            box16.Fill = false;
            box16.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box17
            box17.IconString = "";
            box17.IconSize = 12F;
            box17.IconGap = 5F;
            box17.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box17.Text = "Box 17";
            box17.TextPadding = new Padding(0, 0, 0, 0);
            box17.FontName = "NanumGothic";
            box17.FontSize = 12F;
            box17.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box17.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box17.BackgroundDraw = true;
            box17.LabelColor = null;
            box17.ForeColor = null;
            box17.BorderColor = null;
            box17.Round = null;
            box17.Name = "box17";
            box17.X = 303F;
            box17.Y = 291F;
            box17.Width = 144F;
            box17.Height = 66F;
            box17.Visible = true;
            box17.Enabled = true;
            box17.Fill = false;
            box17.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region box18
            box18.IconString = "";
            box18.IconSize = 12F;
            box18.IconGap = 5F;
            box18.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            box18.Text = "Box 18";
            box18.TextPadding = new Padding(0, 0, 0, 0);
            box18.FontName = "NanumGothic";
            box18.FontSize = 12F;
            box18.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            box18.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            box18.BackgroundDraw = true;
            box18.LabelColor = null;
            box18.ForeColor = null;
            box18.BorderColor = null;
            box18.Round = null;
            box18.Name = "box18";
            box18.X = 453F;
            box18.Y = 291F;
            box18.Width = 294F;
            box18.Height = 66F;
            box18.Visible = true;
            box18.Enabled = true;
            box18.Fill = false;
            box18.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #endregion

            #region add
            Controls.Add(scrpnl);
            scrpnl.Controls.Add(tbl);
            tbl.Controls.Add(pnl, 0, 0, 1, 1);
            tbl.Controls.Add(borderpnl, 1, 0, 1, 1);
            tbl.Controls.Add(boxpnl, 2, 0, 1, 1);
            tbl.Controls.Add(grpbox, 3, 0, 1, 1);
            tbl.Controls.Add(tqb, 0, 1, 4, 1);
            tpTab1.Controls.Add(btnItem1);
            tpTab2.Controls.Add(btnItem2);
            tpTab2.Controls.Add(btnItem3);
            tpTab3.Controls.Add(btnItem4);
            tpTab3.Controls.Add(btnItem5);
            tpTab3.Controls.Add(btnItem6);
            tbl.Controls.Add(dvTableLayoutPanel1, 0, 2, 4, 1);
            dvTableLayoutPanel1.Controls.Add(box1, 0, 0, 1, 3);
            dvTableLayoutPanel1.Controls.Add(box2, 1, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box3, 2, 0, 1, 2);
            dvTableLayoutPanel1.Controls.Add(box4, 3, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box5, 4, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box6, 1, 1, 1, 2);
            dvTableLayoutPanel1.Controls.Add(box7, 3, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box8, 4, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box9, 2, 2, 2, 1);
            dvTableLayoutPanel1.Controls.Add(box10, 4, 2, 1, 2);
            dvTableLayoutPanel1.Controls.Add(box11, 0, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box12, 1, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box13, 2, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box14, 3, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box15, 0, 4, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box16, 1, 4, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box17, 2, 4, 1, 1);
            dvTableLayoutPanel1.Controls.Add(box18, 3, 4, 2, 1);
            #endregion
        }
    }
}
