using System;
using Devinno.Skia.Utils;
using Devinno.Skia.Controls;
using Devinno.Skia.Containers;
using Devinno.Skia.Design;

namespace SampleRPi.Pages
{
    partial class PageInput
    {
        #region declare
        private DvTableLayoutPanel tbl;
        private DvInputText inText;
        private DvInputNumber<Int32> inInt;
        private DvInputBool inBool;
        private DvInputSelector inSelector;
        private DvSelector selector;
        private DvValueInputText vinText;
        private DvValueInputNumber<Int32> vinInt;
        private DvValueInputSelector vinSelector;
        private DvValueInputBool vinBool;
        private DvValueInputCombo vinCombo;
        private DvColorPicker colorPicker;
        private DvDateTimePicker timePicker;
        private DvOnOff oo1;
        private DvCalendar calendar;
        private DvNumberbox nb;
        private DvOnOff oo2;
        private DvOnOff oo3;
        private DvOnOff oo4;
        private DvSwitch sw1;
        private DvSwitch sw2;
        private DvSwitch sw3;
        private DvSwitch sw4;
        private DvWheelPicker wheel;
        private DvComboBox dvComboBox1;
        #endregion

        public void InitializeComponent()
        {
            #region base
            UseMasterPage = true;
            BackgroundDraw = false;
            BackColor = null;
            BackgroundImage = null;
            AnimationType = null;
            Text = "Input";
            IconString = "";
            #endregion

            #region new
            tbl = new DvTableLayoutPanel { Name = nameof(tbl) };
            inText = new DvInputText { Name = nameof(inText) };
            inInt = new DvInputNumber<Int32> { Name = nameof(inInt) };
            inBool = new DvInputBool { Name = nameof(inBool) };
            inSelector = new DvInputSelector { Name = nameof(inSelector) };
            selector = new DvSelector { Name = nameof(selector) };
            vinText = new DvValueInputText { Name = nameof(vinText) };
            vinInt = new DvValueInputNumber<Int32> { Name = nameof(vinInt) };
            vinSelector = new DvValueInputSelector { Name = nameof(vinSelector) };
            vinBool = new DvValueInputBool { Name = nameof(vinBool) };
            vinCombo = new DvValueInputCombo { Name = nameof(vinCombo) };
            colorPicker = new DvColorPicker { Name = nameof(colorPicker) };
            timePicker = new DvDateTimePicker { Name = nameof(timePicker) };
            oo1 = new DvOnOff { Name = nameof(oo1) };
            calendar = new DvCalendar { Name = nameof(calendar) };
            nb = new DvNumberbox { Name = nameof(nb) };
            oo2 = new DvOnOff { Name = nameof(oo2) };
            oo3 = new DvOnOff { Name = nameof(oo3) };
            oo4 = new DvOnOff { Name = nameof(oo4) };
            sw1 = new DvSwitch { Name = nameof(sw1) };
            sw2 = new DvSwitch { Name = nameof(sw2) };
            sw3 = new DvSwitch { Name = nameof(sw3) };
            sw4 = new DvSwitch { Name = nameof(sw4) };
            wheel = new DvWheelPicker { Name = nameof(wheel) };
            dvComboBox1 = new DvComboBox { Name = nameof(dvComboBox1) };
            #endregion

            #region controls
            #region tbl
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 120F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 130F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 250F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Percent, 100F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Name = "tbl";
            tbl.X = 10F;
            tbl.Y = 60F;
            tbl.Width = 780F;
            tbl.Height = 410F;
            tbl.Visible = true;
            tbl.Enabled = true;
            tbl.Fill = true;
            tbl.Margin = new Padding(10, 60, 10, 10);
            #endregion
            #region inText
            inText.Value = "";
            inText.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            inText.FontName = "NanumGothic";
            inText.FontSize = 12F;
            inText.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inText.KeyboardWidth = 600;
            inText.KeyboardHeight = 400;
            inText.BackgroundDraw = true;
            inText.InputColor = null;
            inText.ForeColor = null;
            inText.BorderColor = null;
            inText.Round = null;
            inText.Name = "inText";
            inText.X = 3F;
            inText.Y = 3F;
            inText.Width = 244F;
            inText.Height = 34F;
            inText.Visible = true;
            inText.Enabled = true;
            inText.Fill = false;
            inText.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region inInt
            inInt.Value = 0;
            inInt.Minimum = null;
            inInt.Maximum = null;
            inInt.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            inInt.FormatString = "";
            inInt.FontName = "NanumGothic";
            inInt.FontSize = 12F;
            inInt.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inInt.KeypadWidth = 300;
            inInt.KeypadHeight = 400;
            inInt.BackgroundDraw = true;
            inInt.InputColor = null;
            inInt.ForeColor = null;
            inInt.BorderColor = null;
            inInt.Round = null;
            inInt.Name = "inInt";
            inInt.X = 3F;
            inInt.Y = 43F;
            inInt.Width = 244F;
            inInt.Height = 34F;
            inInt.Visible = true;
            inInt.Enabled = true;
            inInt.Fill = false;
            inInt.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region inBool
            inBool.Value = false;
            inBool.OnText = "ON";
            inBool.OffText = "OFF";
            inBool.FontName = "NanumGothic";
            inBool.FontSize = 12F;
            inBool.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inBool.BackgroundDraw = true;
            inBool.InputColor = null;
            inBool.ForeColor = null;
            inBool.BorderColor = null;
            inBool.Round = null;
            inBool.Name = "inBool";
            inBool.X = 3F;
            inBool.Y = 83F;
            inBool.Width = 244F;
            inBool.Height = 34F;
            inBool.Visible = true;
            inBool.Enabled = true;
            inBool.Fill = false;
            inBool.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region inSelector
            inSelector.Items.Add(new SelectorItem { Text = "Item1",IconString = "" });
            inSelector.Items.Add(new SelectorItem { Text = "Item2",IconString = "" });
            inSelector.Items.Add(new SelectorItem { Text = "Item3",IconString = "" });
            inSelector.Items.Add(new SelectorItem { Text = "Item4",IconString = "" });
            inSelector.Items.Add(new SelectorItem { Text = "Item5",IconString = "" });
            inSelector.FontName = "NanumGothic";
            inSelector.FontSize = 12F;
            inSelector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inSelector.IconSize = 12F;
            inSelector.IconGap = 5F;
            inSelector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            inSelector.SelectedIndex = -1;
            inSelector.BackgroundDraw = true;
            inSelector.InputColor = null;
            inSelector.ForeColor = null;
            inSelector.BorderColor = null;
            inSelector.Round = null;
            inSelector.Name = "inSelector";
            inSelector.X = 3F;
            inSelector.Y = 123F;
            inSelector.Width = 244F;
            inSelector.Height = 34F;
            inSelector.Visible = true;
            inSelector.Enabled = true;
            inSelector.Fill = false;
            inSelector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region selector
            selector.SelectorColor = null;
            selector.ForeColor = null;
            selector.Items.Add(new SelectorItem { Text = "Item1",IconString = "" });
            selector.Items.Add(new SelectorItem { Text = "Item2",IconString = "" });
            selector.Items.Add(new SelectorItem { Text = "Item3",IconString = "" });
            selector.Items.Add(new SelectorItem { Text = "Item4",IconString = "" });
            selector.Items.Add(new SelectorItem { Text = "Item5",IconString = "" });
            selector.BackgroundDraw = true;
            selector.ButtonSize = null;
            selector.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            selector.Round = null;
            selector.FontName = "NanumGothic";
            selector.FontSize = 12F;
            selector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            selector.IconSize = 12F;
            selector.IconGap = 5F;
            selector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            selector.SelectedIndex = -1;
            selector.Name = "selector";
            selector.X = 3F;
            selector.Y = 163F;
            selector.Width = 244F;
            selector.Height = 34F;
            selector.Visible = true;
            selector.Enabled = true;
            selector.Fill = false;
            selector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinText
            vinText.Value = "";
            vinText.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            vinText.FontName = "NanumGothic";
            vinText.FontSize = 12F;
            vinText.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinText.KeyboardWidth = 600;
            vinText.KeyboardHeight = 400;
            vinText.KeyboardMode = Devinno.Skia.Dialogs.KeyboardMode.English;
            vinText.TitleIconString = "";
            vinText.TitleIconSize = 12F;
            vinText.TitleIconGap = 5F;
            vinText.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinText.Title = "Text";
            vinText.TitleFontName = "NanumGothic";
            vinText.TitleFontSize = 12F;
            vinText.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinText.TitleAreaSize = 80F;
            vinText.ButtonAreaSize = null;
            vinText.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinText.BackgroundDraw = true;
            vinText.TitleColor = null;
            vinText.InputColor = null;
            vinText.ButtonColor = null;
            vinText.BorderColor = null;
            vinText.ForeColor = null;
            vinText.Round = null;
            vinText.Name = "vinText";
            vinText.X = 263F;
            vinText.Y = 3F;
            vinText.Width = 244F;
            vinText.Height = 34F;
            vinText.Visible = true;
            vinText.Enabled = true;
            vinText.Fill = false;
            vinText.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinInt
            vinInt.Value = 0;
            vinInt.Minimum = null;
            vinInt.Maximum = null;
            vinInt.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            vinInt.FormatString = "";
            vinInt.FontName = "NanumGothic";
            vinInt.FontSize = 12F;
            vinInt.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinInt.KeypadWidth = 300;
            vinInt.KeypadHeight = 400;
            vinInt.TitleIconString = "";
            vinInt.TitleIconSize = 12F;
            vinInt.TitleIconGap = 5F;
            vinInt.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinInt.Title = "Int";
            vinInt.TitleFontName = "NanumGothic";
            vinInt.TitleFontSize = 12F;
            vinInt.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinInt.TitleAreaSize = 80F;
            vinInt.ButtonAreaSize = null;
            vinInt.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinInt.BackgroundDraw = true;
            vinInt.TitleColor = null;
            vinInt.InputColor = null;
            vinInt.ButtonColor = null;
            vinInt.BorderColor = null;
            vinInt.ForeColor = null;
            vinInt.Round = null;
            vinInt.Name = "vinInt";
            vinInt.X = 263F;
            vinInt.Y = 43F;
            vinInt.Width = 244F;
            vinInt.Height = 34F;
            vinInt.Visible = true;
            vinInt.Enabled = true;
            vinInt.Fill = false;
            vinInt.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinSelector
            vinSelector.Items.Add(new SelectorItem { Text = "Item1",IconString = "" });
            vinSelector.Items.Add(new SelectorItem { Text = "Item2",IconString = "" });
            vinSelector.Items.Add(new SelectorItem { Text = "Item3",IconString = "" });
            vinSelector.Items.Add(new SelectorItem { Text = "Item4",IconString = "" });
            vinSelector.Items.Add(new SelectorItem { Text = "Item5",IconString = "" });
            vinSelector.FontName = "NanumGothic";
            vinSelector.FontSize = 12F;
            vinSelector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinSelector.IconSize = 12F;
            vinSelector.IconGap = 5F;
            vinSelector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinSelector.SelectedIndex = -1;
            vinSelector.TitleIconString = "";
            vinSelector.TitleIconSize = 12F;
            vinSelector.TitleIconGap = 5F;
            vinSelector.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinSelector.Title = "Selector";
            vinSelector.TitleFontName = "NanumGothic";
            vinSelector.TitleFontSize = 12F;
            vinSelector.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinSelector.TitleAreaSize = 80F;
            vinSelector.ButtonAreaSize = null;
            vinSelector.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinSelector.BackgroundDraw = true;
            vinSelector.TitleColor = null;
            vinSelector.InputColor = null;
            vinSelector.ButtonColor = null;
            vinSelector.BorderColor = null;
            vinSelector.ForeColor = null;
            vinSelector.Round = null;
            vinSelector.Name = "vinSelector";
            vinSelector.X = 263F;
            vinSelector.Y = 123F;
            vinSelector.Width = 244F;
            vinSelector.Height = 34F;
            vinSelector.Visible = true;
            vinSelector.Enabled = true;
            vinSelector.Fill = false;
            vinSelector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinBool
            vinBool.Value = false;
            vinBool.OnText = "ON";
            vinBool.OffText = "OFF";
            vinBool.FontName = "NanumGothic";
            vinBool.FontSize = 12F;
            vinBool.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinBool.TitleIconString = "";
            vinBool.TitleIconSize = 12F;
            vinBool.TitleIconGap = 5F;
            vinBool.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinBool.Title = "Bool";
            vinBool.TitleFontName = "NanumGothic";
            vinBool.TitleFontSize = 12F;
            vinBool.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinBool.TitleAreaSize = 80F;
            vinBool.ButtonAreaSize = null;
            vinBool.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinBool.BackgroundDraw = true;
            vinBool.TitleColor = null;
            vinBool.InputColor = null;
            vinBool.ButtonColor = null;
            vinBool.BorderColor = null;
            vinBool.ForeColor = null;
            vinBool.Round = null;
            vinBool.Name = "vinBool";
            vinBool.X = 263F;
            vinBool.Y = 83F;
            vinBool.Width = 244F;
            vinBool.Height = 34F;
            vinBool.Visible = true;
            vinBool.Enabled = true;
            vinBool.Fill = false;
            vinBool.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinCombo
            vinCombo.Items.Add(new ComboBoxItem { Text = "Item1",IconString = "" });
            vinCombo.Items.Add(new ComboBoxItem { Text = "Item2",IconString = "" });
            vinCombo.Items.Add(new ComboBoxItem { Text = "Item3",IconString = "" });
            vinCombo.Items.Add(new ComboBoxItem { Text = "Item4",IconString = "" });
            vinCombo.Items.Add(new ComboBoxItem { Text = "Item5",IconString = "" });
            vinCombo.FontName = "NanumGothic";
            vinCombo.FontSize = 12F;
            vinCombo.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinCombo.IconSize = 12F;
            vinCombo.IconGap = 5F;
            vinCombo.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinCombo.SelectedIndex = -1;
            vinCombo.MaximumViewCount = 8;
            vinCombo.ItemHeight = 30;
            vinCombo.TitleIconString = "";
            vinCombo.TitleIconSize = 12F;
            vinCombo.TitleIconGap = 5F;
            vinCombo.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinCombo.Title = "Combbo";
            vinCombo.TitleFontName = "NanumGothic";
            vinCombo.TitleFontSize = 12F;
            vinCombo.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinCombo.TitleAreaSize = 80F;
            vinCombo.ButtonAreaSize = null;
            vinCombo.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinCombo.BackgroundDraw = true;
            vinCombo.TitleColor = null;
            vinCombo.InputColor = null;
            vinCombo.ButtonColor = null;
            vinCombo.BorderColor = null;
            vinCombo.ForeColor = null;
            vinCombo.Round = null;
            vinCombo.Name = "vinCombo";
            vinCombo.X = 263F;
            vinCombo.Y = 163F;
            vinCombo.Width = 244F;
            vinCombo.Height = 34F;
            vinCombo.Visible = true;
            vinCombo.Enabled = true;
            vinCombo.Fill = false;
            vinCombo.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region colorPicker
            colorPicker.Value = Util.FromArgb(255, 255, 255, 255);
            colorPicker.Code = Devinno.Skia.Tools.ColorCodeType.CodeRGB;
            colorPicker.FontName = "NanumGothic";
            colorPicker.FontSize = 12F;
            colorPicker.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            colorPicker.ButtonIconSize = 14;
            colorPicker.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            colorPicker.TitleIconString = "";
            colorPicker.TitleIconSize = 12F;
            colorPicker.TitleIconGap = 5F;
            colorPicker.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            colorPicker.Title = "Color";
            colorPicker.TitleFontName = "NanumGothic";
            colorPicker.TitleFontSize = 12F;
            colorPicker.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            colorPicker.TitleAreaSize = 70F;
            colorPicker.ButtonAreaSize = 44F;
            colorPicker.BackgroundDraw = true;
            colorPicker.TitleColor = null;
            colorPicker.ValueColor = null;
            colorPicker.ButtonColor = null;
            colorPicker.BorderColor = null;
            colorPicker.ForeColor = null;
            colorPicker.Round = null;
            colorPicker.Name = "colorPicker";
            colorPicker.X = 523F;
            colorPicker.Y = 363F;
            colorPicker.Width = 254F;
            colorPicker.Height = 44F;
            colorPicker.Visible = true;
            colorPicker.Enabled = true;
            colorPicker.Fill = false;
            colorPicker.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region timePicker
            timePicker.Type = Devinno.Skia.Design.DateTimePickerMode.DateTime;
            timePicker.FontName = "NanumGothic";
            timePicker.FontSize = 12F;
            timePicker.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            timePicker.ButtonIconSize = 14;
            timePicker.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            timePicker.TitleIconString = "";
            timePicker.TitleIconSize = 12F;
            timePicker.TitleIconGap = 5F;
            timePicker.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            timePicker.Title = "DateTime";
            timePicker.TitleFontName = "NanumGothic";
            timePicker.TitleFontSize = 12F;
            timePicker.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            timePicker.TitleAreaSize = 70F;
            timePicker.ButtonAreaSize = 44F;
            timePicker.BackgroundDraw = true;
            timePicker.TitleColor = null;
            timePicker.ValueColor = null;
            timePicker.ButtonColor = null;
            timePicker.BorderColor = null;
            timePicker.ForeColor = null;
            timePicker.Round = null;
            timePicker.Name = "timePicker";
            timePicker.X = 523F;
            timePicker.Y = 313F;
            timePicker.Width = 254F;
            timePicker.Height = 44F;
            timePicker.Visible = true;
            timePicker.Enabled = true;
            timePicker.Fill = false;
            timePicker.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo1
            oo1.CursorColor = null;
            oo1.OnBoxColor = null;
            oo1.OffBoxColor = null;
            oo1.OnTextColor = null;
            oo1.OffTextColor = null;
            oo1.OnText = "ON";
            oo1.OffText = "OFF";
            oo1.FontName = "NanumGothic";
            oo1.FontSize = 12F;
            oo1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo1.CursorPadding = 5F;
            oo1.OnOff = false;
            oo1.Name = "oo1";
            oo1.X = 3F;
            oo1.Y = 213F;
            oo1.Width = 114F;
            oo1.Height = 44F;
            oo1.Visible = true;
            oo1.Enabled = true;
            oo1.Fill = false;
            oo1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region calendar
            calendar.ForeColor = null;
            calendar.BoxColor = null;
            calendar.SelectColor = null;
            calendar.MultiSelect = false;
            calendar.NoneSelect = false;
            calendar.BackgroundDraw = true;
            calendar.FontName = "NanumGothic";
            calendar.FontSize = 12F;
            calendar.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            calendar.Name = "calendar";
            calendar.X = 523F;
            calendar.Y = 3F;
            calendar.Width = 254F;
            calendar.Height = 194F;
            calendar.Visible = true;
            calendar.Enabled = true;
            calendar.Fill = false;
            calendar.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region nb
            nb.Value = 0;
            nb.Minimum = 0;
            nb.Maximum = 100;
            nb.Tick = 1;
            nb.FormatString = "";
            nb.FontName = "NanumGothic";
            nb.FontSize = 12F;
            nb.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb.ButtonIconSize = 14;
            nb.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            nb.TitleIconString = "";
            nb.TitleIconSize = 12F;
            nb.TitleIconGap = 5F;
            nb.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            nb.Title = "Number";
            nb.TitleFontName = "NanumGothic";
            nb.TitleFontSize = 12F;
            nb.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb.TitleAreaSize = 70F;
            nb.ButtonAreaSize = 88F;
            nb.BackgroundDraw = true;
            nb.TitleColor = null;
            nb.ValueColor = null;
            nb.ButtonColor = null;
            nb.BorderColor = null;
            nb.ForeColor = null;
            nb.Round = null;
            nb.Name = "nb";
            nb.X = 523F;
            nb.Y = 263F;
            nb.Width = 254F;
            nb.Height = 44F;
            nb.Visible = true;
            nb.Enabled = true;
            nb.Fill = false;
            nb.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo2
            oo2.CursorColor = null;
            oo2.OnBoxColor = Util.FromArgb(255, 0, 128, 0);
            oo2.OffBoxColor = null;
            oo2.OnTextColor = null;
            oo2.OffTextColor = null;
            oo2.OnText = "ON";
            oo2.OffText = "OFF";
            oo2.FontName = "NanumGothic";
            oo2.FontSize = 12F;
            oo2.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo2.CursorPadding = 5F;
            oo2.OnOff = false;
            oo2.Name = "oo2";
            oo2.X = 3F;
            oo2.Y = 263F;
            oo2.Width = 114F;
            oo2.Height = 44F;
            oo2.Visible = true;
            oo2.Enabled = true;
            oo2.Fill = false;
            oo2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo3
            oo3.CursorColor = null;
            oo3.OnBoxColor = Util.FromArgb(255, 0, 0, 255);
            oo3.OffBoxColor = null;
            oo3.OnTextColor = null;
            oo3.OffTextColor = null;
            oo3.OnText = "ON";
            oo3.OffText = "OFF";
            oo3.FontName = "NanumGothic";
            oo3.FontSize = 12F;
            oo3.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo3.CursorPadding = 5F;
            oo3.OnOff = false;
            oo3.Name = "oo3";
            oo3.X = 3F;
            oo3.Y = 313F;
            oo3.Width = 114F;
            oo3.Height = 44F;
            oo3.Visible = true;
            oo3.Enabled = true;
            oo3.Fill = false;
            oo3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo4
            oo4.CursorColor = null;
            oo4.OnBoxColor = Util.FromArgb(255, 90, 90, 90);
            oo4.OffBoxColor = null;
            oo4.OnTextColor = null;
            oo4.OffTextColor = null;
            oo4.OnText = "ON";
            oo4.OffText = "OFF";
            oo4.FontName = "NanumGothic";
            oo4.FontSize = 12F;
            oo4.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo4.CursorPadding = 5F;
            oo4.OnOff = false;
            oo4.Name = "oo4";
            oo4.X = 3F;
            oo4.Y = 363F;
            oo4.Width = 114F;
            oo4.Height = 44F;
            oo4.Visible = true;
            oo4.Enabled = true;
            oo4.Fill = false;
            oo4.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw1
            sw1.OnBoxColor = null;
            sw1.OffBoxColor = null;
            sw1.SwitchColor = null;
            sw1.ForeColor = null;
            sw1.OnIconString = "";
            sw1.OnIconSize = 12F;
            sw1.OnIconGap = 5F;
            sw1.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw1.OnText = "ON";
            sw1.OnTextPadding = new Padding(0, 0, 0, 0);
            sw1.OnFontName = "NanumGothic";
            sw1.OnFontSize = 12F;
            sw1.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw1.OffIconString = "";
            sw1.OffIconSize = 12F;
            sw1.OffIconGap = 5F;
            sw1.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw1.OffText = "OFF";
            sw1.OffTextPadding = new Padding(0, 0, 0, 0);
            sw1.OffFontName = "NanumGothic";
            sw1.OffFontSize = 12F;
            sw1.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw1.Corner = null;
            sw1.SwitchPadding = 5F;
            sw1.OnOff = false;
            sw1.Name = "sw1";
            sw1.X = 123F;
            sw1.Y = 213F;
            sw1.Width = 124F;
            sw1.Height = 44F;
            sw1.Visible = true;
            sw1.Enabled = true;
            sw1.Fill = false;
            sw1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw2
            sw2.OnBoxColor = Util.FromArgb(255, 0, 128, 0);
            sw2.OffBoxColor = null;
            sw2.SwitchColor = null;
            sw2.ForeColor = null;
            sw2.OnIconString = "";
            sw2.OnIconSize = 12F;
            sw2.OnIconGap = 5F;
            sw2.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw2.OnText = "ON";
            sw2.OnTextPadding = new Padding(0, 0, 0, 0);
            sw2.OnFontName = "NanumGothic";
            sw2.OnFontSize = 12F;
            sw2.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw2.OffIconString = "";
            sw2.OffIconSize = 12F;
            sw2.OffIconGap = 5F;
            sw2.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw2.OffText = "OFF";
            sw2.OffTextPadding = new Padding(0, 0, 0, 0);
            sw2.OffFontName = "NanumGothic";
            sw2.OffFontSize = 12F;
            sw2.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw2.Corner = null;
            sw2.SwitchPadding = 5F;
            sw2.OnOff = false;
            sw2.Name = "sw2";
            sw2.X = 123F;
            sw2.Y = 263F;
            sw2.Width = 124F;
            sw2.Height = 44F;
            sw2.Visible = true;
            sw2.Enabled = true;
            sw2.Fill = false;
            sw2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw3
            sw3.OnBoxColor = Util.FromArgb(255, 0, 0, 255);
            sw3.OffBoxColor = null;
            sw3.SwitchColor = null;
            sw3.ForeColor = null;
            sw3.OnIconString = "";
            sw3.OnIconSize = 12F;
            sw3.OnIconGap = 5F;
            sw3.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw3.OnText = "ON";
            sw3.OnTextPadding = new Padding(0, 0, 0, 0);
            sw3.OnFontName = "NanumGothic";
            sw3.OnFontSize = 12F;
            sw3.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw3.OffIconString = "";
            sw3.OffIconSize = 12F;
            sw3.OffIconGap = 5F;
            sw3.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw3.OffText = "OFF";
            sw3.OffTextPadding = new Padding(0, 0, 0, 0);
            sw3.OffFontName = "NanumGothic";
            sw3.OffFontSize = 12F;
            sw3.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw3.Corner = null;
            sw3.SwitchPadding = 5F;
            sw3.OnOff = false;
            sw3.Name = "sw3";
            sw3.X = 123F;
            sw3.Y = 313F;
            sw3.Width = 124F;
            sw3.Height = 44F;
            sw3.Visible = true;
            sw3.Enabled = true;
            sw3.Fill = false;
            sw3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw4
            sw4.OnBoxColor = Util.FromArgb(255, 90, 90, 90);
            sw4.OffBoxColor = null;
            sw4.SwitchColor = null;
            sw4.ForeColor = null;
            sw4.OnIconString = "";
            sw4.OnIconSize = 12F;
            sw4.OnIconGap = 5F;
            sw4.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw4.OnText = "ON";
            sw4.OnTextPadding = new Padding(0, 0, 0, 0);
            sw4.OnFontName = "NanumGothic";
            sw4.OnFontSize = 12F;
            sw4.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw4.OffIconString = "";
            sw4.OffIconSize = 12F;
            sw4.OffIconGap = 5F;
            sw4.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw4.OffText = "OFF";
            sw4.OffTextPadding = new Padding(0, 0, 0, 0);
            sw4.OffFontName = "NanumGothic";
            sw4.OffFontSize = 12F;
            sw4.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw4.Corner = null;
            sw4.SwitchPadding = 5F;
            sw4.OnOff = false;
            sw4.Name = "sw4";
            sw4.X = 123F;
            sw4.Y = 363F;
            sw4.Width = 124F;
            sw4.Height = 44F;
            sw4.Visible = true;
            sw4.Enabled = true;
            sw4.Fill = false;
            sw4.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region wheel
            wheel.ForeColor = null;
            wheel.BorderColor = null;
            wheel.BorderWidth = 1;
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item1", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item2", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item3", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item4", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item5", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item6", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item7", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item8", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item9", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.Items.Add(new DvTextIcon { IconString = "", IconSize = 12, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "Item10", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            wheel.ItemHeight = 30;
            wheel.SelectedIndex = 0;
            wheel.FontName = "NanumGothic";
            wheel.FontSize = 12F;
            wheel.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            wheel.IconSize = 12F;
            wheel.IconGap = 5F;
            wheel.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            wheel.TouchMode = true;
            wheel.Name = "wheel";
            wheel.X = 263F;
            wheel.Y = 213F;
            wheel.Width = 244F;
            wheel.Height = 194F;
            wheel.Visible = true;
            wheel.Enabled = true;
            wheel.Fill = false;
            wheel.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region dvComboBox1
            dvComboBox1.BoxColor = null;
            dvComboBox1.ForeColor = null;
            dvComboBox1.SelectedColor = Util.FromArgb(255, 255, 165, 0);
            dvComboBox1.FontName = "NanumGothic";
            dvComboBox1.FontSize = 12F;
            dvComboBox1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            dvComboBox1.IconSize = 12F;
            dvComboBox1.IconGap = 5F;
            dvComboBox1.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            dvComboBox1.Items.Add(new ComboBoxItem { Text = "Item1",IconString = "" });
            dvComboBox1.Items.Add(new ComboBoxItem { Text = "Item2",IconString = "" });
            dvComboBox1.Items.Add(new ComboBoxItem { Text = "Item3",IconString = "" });
            dvComboBox1.Items.Add(new ComboBoxItem { Text = "Item4",IconString = "" });
            dvComboBox1.Items.Add(new ComboBoxItem { Text = "Item5",IconString = "" });
            dvComboBox1.SelectedIndex = -1;
            dvComboBox1.ButtonWidth = 40;
            dvComboBox1.MaximumViewCount = 8;
            dvComboBox1.ItemHeight = 30;
            dvComboBox1.Name = "dvComboBox1";
            dvComboBox1.X = 523F;
            dvComboBox1.Y = 213F;
            dvComboBox1.Width = 254F;
            dvComboBox1.Height = 44F;
            dvComboBox1.Visible = true;
            dvComboBox1.Enabled = true;
            dvComboBox1.Fill = false;
            dvComboBox1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #endregion

            #region add
            Controls.Add(tbl);
            tbl.Controls.Add(inText, 0, 0, 2, 1);
            tbl.Controls.Add(inInt, 0, 1, 2, 1);
            tbl.Controls.Add(inBool, 0, 2, 2, 1);
            tbl.Controls.Add(inSelector, 0, 3, 2, 1);
            tbl.Controls.Add(selector, 0, 4, 2, 1);
            tbl.Controls.Add(vinText, 3, 0, 1, 1);
            tbl.Controls.Add(vinInt, 3, 1, 1, 1);
            tbl.Controls.Add(vinSelector, 3, 3, 1, 1);
            tbl.Controls.Add(vinBool, 3, 2, 1, 1);
            tbl.Controls.Add(vinCombo, 3, 4, 1, 1);
            tbl.Controls.Add(colorPicker, 5, 9, 1, 1);
            tbl.Controls.Add(timePicker, 5, 8, 1, 1);
            tbl.Controls.Add(oo1, 0, 6, 1, 1);
            tbl.Controls.Add(calendar, 5, 0, 1, 5);
            tbl.Controls.Add(nb, 5, 7, 1, 1);
            tbl.Controls.Add(oo2, 0, 7, 1, 1);
            tbl.Controls.Add(oo3, 0, 8, 1, 1);
            tbl.Controls.Add(oo4, 0, 9, 1, 1);
            tbl.Controls.Add(sw1, 1, 6, 1, 1);
            tbl.Controls.Add(sw2, 1, 7, 1, 1);
            tbl.Controls.Add(sw3, 1, 8, 1, 1);
            tbl.Controls.Add(sw4, 1, 9, 1, 1);
            tbl.Controls.Add(wheel, 3, 6, 1, 4);
            tbl.Controls.Add(dvComboBox1, 5, 6, 1, 1);
            #endregion
        }
    }
}
