using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Devinno.Skia.Utils;
using Devinno.Skia.Controls;
using Devinno.Skia.Containers;
using Devinno.Skia.Design;

namespace SampleRPi.Pages
{
    partial class PageDialogs
    {
        #region declare
        private DvTableLayoutPanel dvTableLayoutPanel1;
        private DvButton btnKeypadInt;
        private DvButton btnKeypadFloat;
        private DvButton btnKeypadPasswd;
        private DvButton btnKeypadHex;
        private DvButton btnKeyboardKor;
        private DvButton btnKeyboardEng;
        private DvButton btnKeyboardNum;
        private DvButton btnKeyboardEngOnly;
        private DvButton btnSelSelector;
        private DvButton btnSelWheel;
        private DvButton btnSelRadio;
        private DvButton btnSelCheck;
        private DvButton btnInputBox;
        private DvButton btnColorPicker;
        private DvButton btnTimePicker;
        private DvButton btnMessageOK;
        private DvLabel lblKeypad;
        private DvLabel lblKeyboard;
        private DvLabel lblSelector;
        private DvLabel lblOther;
        private DvButton btnMessageOC;
        private DvButton btnMessageYN;
        private DvButton btnMessageYNC;
        private DvLabel lblMessage;
        private DvButton btnCustomWindow;
        private DvLabel dvLabel1;
        #endregion

        public void InitializeComponent()
        {
            #region base
            UseMasterPage = true;
            BackgroundDraw = false;
            BackColor = null;
            BackgroundImage = null;
            AnimationType = null;
            Text = "Dialogs";
            IconString = "";
            #endregion

            #region new
            dvTableLayoutPanel1 = new DvTableLayoutPanel { Name = nameof(dvTableLayoutPanel1) };
            btnKeypadInt = new DvButton { Name = nameof(btnKeypadInt) };
            btnKeypadFloat = new DvButton { Name = nameof(btnKeypadFloat) };
            btnKeypadPasswd = new DvButton { Name = nameof(btnKeypadPasswd) };
            btnKeypadHex = new DvButton { Name = nameof(btnKeypadHex) };
            btnKeyboardKor = new DvButton { Name = nameof(btnKeyboardKor) };
            btnKeyboardEng = new DvButton { Name = nameof(btnKeyboardEng) };
            btnKeyboardNum = new DvButton { Name = nameof(btnKeyboardNum) };
            btnKeyboardEngOnly = new DvButton { Name = nameof(btnKeyboardEngOnly) };
            btnSelSelector = new DvButton { Name = nameof(btnSelSelector) };
            btnSelWheel = new DvButton { Name = nameof(btnSelWheel) };
            btnSelRadio = new DvButton { Name = nameof(btnSelRadio) };
            btnSelCheck = new DvButton { Name = nameof(btnSelCheck) };
            btnInputBox = new DvButton { Name = nameof(btnInputBox) };
            btnColorPicker = new DvButton { Name = nameof(btnColorPicker) };
            btnTimePicker = new DvButton { Name = nameof(btnTimePicker) };
            btnMessageOK = new DvButton { Name = nameof(btnMessageOK) };
            lblKeypad = new DvLabel { Name = nameof(lblKeypad) };
            lblKeyboard = new DvLabel { Name = nameof(lblKeyboard) };
            lblSelector = new DvLabel { Name = nameof(lblSelector) };
            lblOther = new DvLabel { Name = nameof(lblOther) };
            btnMessageOC = new DvButton { Name = nameof(btnMessageOC) };
            btnMessageYN = new DvButton { Name = nameof(btnMessageYN) };
            btnMessageYNC = new DvButton { Name = nameof(btnMessageYNC) };
            lblMessage = new DvLabel { Name = nameof(lblMessage) };
            btnCustomWindow = new DvButton { Name = nameof(btnCustomWindow) };
            dvLabel1 = new DvLabel { Name = nameof(dvLabel1) };
            #endregion

            #region controls
            #region dvTableLayoutPanel1
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            dvTableLayoutPanel1.Columns.Add(new SizeInfo(DvSizeMode.Percent, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 46F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 46F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 46F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 46F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 20F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 46F));
            dvTableLayoutPanel1.Rows.Add(new SizeInfo(DvSizeMode.Percent, 100F));
            dvTableLayoutPanel1.Name = "dvTableLayoutPanel1";
            dvTableLayoutPanel1.X = 10F;
            dvTableLayoutPanel1.Y = 60F;
            dvTableLayoutPanel1.Width = 780F;
            dvTableLayoutPanel1.Height = 410F;
            dvTableLayoutPanel1.Visible = true;
            dvTableLayoutPanel1.Enabled = true;
            dvTableLayoutPanel1.Fill = true;
            dvTableLayoutPanel1.Margin = new Padding(10, 60, 10, 10);
            #endregion
            #region btnKeypadInt
            btnKeypadInt.IconString = "";
            btnKeypadInt.IconSize = 12F;
            btnKeypadInt.IconGap = 5F;
            btnKeypadInt.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeypadInt.Text = "Keypad : int";
            btnKeypadInt.TextPadding = new Padding(0, 0, 0, 0);
            btnKeypadInt.FontName = "NanumGothic";
            btnKeypadInt.FontSize = 12F;
            btnKeypadInt.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeypadInt.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeypadInt.BackgroundDraw = true;
            btnKeypadInt.ButtonColor = null;
            btnKeypadInt.ForeColor = null;
            btnKeypadInt.BorderColor = null;
            btnKeypadInt.Round = null;
            btnKeypadInt.Gradient = true;
            btnKeypadInt.Clickable = true;
            btnKeypadInt.Name = "btnKeypadInt";
            btnKeypadInt.X = 3F;
            btnKeypadInt.Y = 3F;
            btnKeypadInt.Width = 142F;
            btnKeypadInt.Height = 40F;
            btnKeypadInt.Visible = true;
            btnKeypadInt.Enabled = true;
            btnKeypadInt.Fill = false;
            btnKeypadInt.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeypadFloat
            btnKeypadFloat.IconString = "";
            btnKeypadFloat.IconSize = 12F;
            btnKeypadFloat.IconGap = 5F;
            btnKeypadFloat.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeypadFloat.Text = "Keypad : float";
            btnKeypadFloat.TextPadding = new Padding(0, 0, 0, 0);
            btnKeypadFloat.FontName = "NanumGothic";
            btnKeypadFloat.FontSize = 12F;
            btnKeypadFloat.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeypadFloat.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeypadFloat.BackgroundDraw = true;
            btnKeypadFloat.ButtonColor = null;
            btnKeypadFloat.ForeColor = null;
            btnKeypadFloat.BorderColor = null;
            btnKeypadFloat.Round = null;
            btnKeypadFloat.Gradient = true;
            btnKeypadFloat.Clickable = true;
            btnKeypadFloat.Name = "btnKeypadFloat";
            btnKeypadFloat.X = 3F;
            btnKeypadFloat.Y = 49F;
            btnKeypadFloat.Width = 142F;
            btnKeypadFloat.Height = 40F;
            btnKeypadFloat.Visible = true;
            btnKeypadFloat.Enabled = true;
            btnKeypadFloat.Fill = false;
            btnKeypadFloat.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeypadPasswd
            btnKeypadPasswd.IconString = "";
            btnKeypadPasswd.IconSize = 12F;
            btnKeypadPasswd.IconGap = 5F;
            btnKeypadPasswd.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeypadPasswd.Text = "Keypad : passwd";
            btnKeypadPasswd.TextPadding = new Padding(0, 0, 0, 0);
            btnKeypadPasswd.FontName = "NanumGothic";
            btnKeypadPasswd.FontSize = 12F;
            btnKeypadPasswd.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeypadPasswd.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeypadPasswd.BackgroundDraw = true;
            btnKeypadPasswd.ButtonColor = null;
            btnKeypadPasswd.ForeColor = null;
            btnKeypadPasswd.BorderColor = null;
            btnKeypadPasswd.Round = null;
            btnKeypadPasswd.Gradient = true;
            btnKeypadPasswd.Clickable = true;
            btnKeypadPasswd.Name = "btnKeypadPasswd";
            btnKeypadPasswd.X = 3F;
            btnKeypadPasswd.Y = 95F;
            btnKeypadPasswd.Width = 142F;
            btnKeypadPasswd.Height = 40F;
            btnKeypadPasswd.Visible = true;
            btnKeypadPasswd.Enabled = true;
            btnKeypadPasswd.Fill = false;
            btnKeypadPasswd.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeypadHex
            btnKeypadHex.IconString = "";
            btnKeypadHex.IconSize = 12F;
            btnKeypadHex.IconGap = 5F;
            btnKeypadHex.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeypadHex.Text = "Keypad : hex";
            btnKeypadHex.TextPadding = new Padding(0, 0, 0, 0);
            btnKeypadHex.FontName = "NanumGothic";
            btnKeypadHex.FontSize = 12F;
            btnKeypadHex.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeypadHex.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeypadHex.BackgroundDraw = true;
            btnKeypadHex.ButtonColor = null;
            btnKeypadHex.ForeColor = null;
            btnKeypadHex.BorderColor = null;
            btnKeypadHex.Round = null;
            btnKeypadHex.Gradient = true;
            btnKeypadHex.Clickable = true;
            btnKeypadHex.Name = "btnKeypadHex";
            btnKeypadHex.X = 3F;
            btnKeypadHex.Y = 141F;
            btnKeypadHex.Width = 142F;
            btnKeypadHex.Height = 40F;
            btnKeypadHex.Visible = true;
            btnKeypadHex.Enabled = true;
            btnKeypadHex.Fill = false;
            btnKeypadHex.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeyboardKor
            btnKeyboardKor.IconString = "";
            btnKeyboardKor.IconSize = 12F;
            btnKeyboardKor.IconGap = 5F;
            btnKeyboardKor.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeyboardKor.Text = "Keyboard ; KOR";
            btnKeyboardKor.TextPadding = new Padding(0, 0, 0, 0);
            btnKeyboardKor.FontName = "NanumGothic";
            btnKeyboardKor.FontSize = 12F;
            btnKeyboardKor.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeyboardKor.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeyboardKor.BackgroundDraw = true;
            btnKeyboardKor.ButtonColor = null;
            btnKeyboardKor.ForeColor = null;
            btnKeyboardKor.BorderColor = null;
            btnKeyboardKor.Round = null;
            btnKeyboardKor.Gradient = true;
            btnKeyboardKor.Clickable = true;
            btnKeyboardKor.Name = "btnKeyboardKor";
            btnKeyboardKor.X = 161F;
            btnKeyboardKor.Y = 3F;
            btnKeyboardKor.Width = 142F;
            btnKeyboardKor.Height = 40F;
            btnKeyboardKor.Visible = true;
            btnKeyboardKor.Enabled = true;
            btnKeyboardKor.Fill = false;
            btnKeyboardKor.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeyboardEng
            btnKeyboardEng.IconString = "";
            btnKeyboardEng.IconSize = 12F;
            btnKeyboardEng.IconGap = 5F;
            btnKeyboardEng.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeyboardEng.Text = "Keyboard : ENG";
            btnKeyboardEng.TextPadding = new Padding(0, 0, 0, 0);
            btnKeyboardEng.FontName = "NanumGothic";
            btnKeyboardEng.FontSize = 12F;
            btnKeyboardEng.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeyboardEng.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeyboardEng.BackgroundDraw = true;
            btnKeyboardEng.ButtonColor = null;
            btnKeyboardEng.ForeColor = null;
            btnKeyboardEng.BorderColor = null;
            btnKeyboardEng.Round = null;
            btnKeyboardEng.Gradient = true;
            btnKeyboardEng.Clickable = true;
            btnKeyboardEng.Name = "btnKeyboardEng";
            btnKeyboardEng.X = 161F;
            btnKeyboardEng.Y = 49F;
            btnKeyboardEng.Width = 142F;
            btnKeyboardEng.Height = 40F;
            btnKeyboardEng.Visible = true;
            btnKeyboardEng.Enabled = true;
            btnKeyboardEng.Fill = false;
            btnKeyboardEng.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeyboardNum
            btnKeyboardNum.IconString = "";
            btnKeyboardNum.IconSize = 12F;
            btnKeyboardNum.IconGap = 5F;
            btnKeyboardNum.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeyboardNum.Text = "Keyboard : NUM";
            btnKeyboardNum.TextPadding = new Padding(0, 0, 0, 0);
            btnKeyboardNum.FontName = "NanumGothic";
            btnKeyboardNum.FontSize = 12F;
            btnKeyboardNum.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeyboardNum.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeyboardNum.BackgroundDraw = true;
            btnKeyboardNum.ButtonColor = null;
            btnKeyboardNum.ForeColor = null;
            btnKeyboardNum.BorderColor = null;
            btnKeyboardNum.Round = null;
            btnKeyboardNum.Gradient = true;
            btnKeyboardNum.Clickable = true;
            btnKeyboardNum.Name = "btnKeyboardNum";
            btnKeyboardNum.X = 161F;
            btnKeyboardNum.Y = 95F;
            btnKeyboardNum.Width = 142F;
            btnKeyboardNum.Height = 40F;
            btnKeyboardNum.Visible = true;
            btnKeyboardNum.Enabled = true;
            btnKeyboardNum.Fill = false;
            btnKeyboardNum.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnKeyboardEngOnly
            btnKeyboardEngOnly.IconString = "";
            btnKeyboardEngOnly.IconSize = 12F;
            btnKeyboardEngOnly.IconGap = 5F;
            btnKeyboardEngOnly.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnKeyboardEngOnly.Text = "Keyboard : ENG Only";
            btnKeyboardEngOnly.TextPadding = new Padding(0, 0, 0, 0);
            btnKeyboardEngOnly.FontName = "NanumGothic";
            btnKeyboardEngOnly.FontSize = 12F;
            btnKeyboardEngOnly.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnKeyboardEngOnly.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnKeyboardEngOnly.BackgroundDraw = true;
            btnKeyboardEngOnly.ButtonColor = null;
            btnKeyboardEngOnly.ForeColor = null;
            btnKeyboardEngOnly.BorderColor = null;
            btnKeyboardEngOnly.Round = null;
            btnKeyboardEngOnly.Gradient = true;
            btnKeyboardEngOnly.Clickable = true;
            btnKeyboardEngOnly.Name = "btnKeyboardEngOnly";
            btnKeyboardEngOnly.X = 161F;
            btnKeyboardEngOnly.Y = 141F;
            btnKeyboardEngOnly.Width = 142F;
            btnKeyboardEngOnly.Height = 40F;
            btnKeyboardEngOnly.Visible = true;
            btnKeyboardEngOnly.Enabled = true;
            btnKeyboardEngOnly.Fill = false;
            btnKeyboardEngOnly.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnSelSelector
            btnSelSelector.IconString = "";
            btnSelSelector.IconSize = 12F;
            btnSelSelector.IconGap = 5F;
            btnSelSelector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnSelSelector.Text = "Selector : Selector";
            btnSelSelector.TextPadding = new Padding(0, 0, 0, 0);
            btnSelSelector.FontName = "NanumGothic";
            btnSelSelector.FontSize = 12F;
            btnSelSelector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnSelSelector.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnSelSelector.BackgroundDraw = true;
            btnSelSelector.ButtonColor = null;
            btnSelSelector.ForeColor = null;
            btnSelSelector.BorderColor = null;
            btnSelSelector.Round = null;
            btnSelSelector.Gradient = true;
            btnSelSelector.Clickable = true;
            btnSelSelector.Name = "btnSelSelector";
            btnSelSelector.X = 319F;
            btnSelSelector.Y = 3F;
            btnSelSelector.Width = 142F;
            btnSelSelector.Height = 40F;
            btnSelSelector.Visible = true;
            btnSelSelector.Enabled = true;
            btnSelSelector.Fill = false;
            btnSelSelector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnSelWheel
            btnSelWheel.IconString = "";
            btnSelWheel.IconSize = 12F;
            btnSelWheel.IconGap = 5F;
            btnSelWheel.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnSelWheel.Text = "Selector : Wheel";
            btnSelWheel.TextPadding = new Padding(0, 0, 0, 0);
            btnSelWheel.FontName = "NanumGothic";
            btnSelWheel.FontSize = 12F;
            btnSelWheel.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnSelWheel.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnSelWheel.BackgroundDraw = true;
            btnSelWheel.ButtonColor = null;
            btnSelWheel.ForeColor = null;
            btnSelWheel.BorderColor = null;
            btnSelWheel.Round = null;
            btnSelWheel.Gradient = true;
            btnSelWheel.Clickable = true;
            btnSelWheel.Name = "btnSelWheel";
            btnSelWheel.X = 319F;
            btnSelWheel.Y = 49F;
            btnSelWheel.Width = 142F;
            btnSelWheel.Height = 40F;
            btnSelWheel.Visible = true;
            btnSelWheel.Enabled = true;
            btnSelWheel.Fill = false;
            btnSelWheel.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnSelRadio
            btnSelRadio.IconString = "";
            btnSelRadio.IconSize = 12F;
            btnSelRadio.IconGap = 5F;
            btnSelRadio.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnSelRadio.Text = "Selector : Radio";
            btnSelRadio.TextPadding = new Padding(0, 0, 0, 0);
            btnSelRadio.FontName = "NanumGothic";
            btnSelRadio.FontSize = 12F;
            btnSelRadio.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnSelRadio.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnSelRadio.BackgroundDraw = true;
            btnSelRadio.ButtonColor = null;
            btnSelRadio.ForeColor = null;
            btnSelRadio.BorderColor = null;
            btnSelRadio.Round = null;
            btnSelRadio.Gradient = true;
            btnSelRadio.Clickable = true;
            btnSelRadio.Name = "btnSelRadio";
            btnSelRadio.X = 319F;
            btnSelRadio.Y = 95F;
            btnSelRadio.Width = 142F;
            btnSelRadio.Height = 40F;
            btnSelRadio.Visible = true;
            btnSelRadio.Enabled = true;
            btnSelRadio.Fill = false;
            btnSelRadio.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnSelCheck
            btnSelCheck.IconString = "";
            btnSelCheck.IconSize = 12F;
            btnSelCheck.IconGap = 5F;
            btnSelCheck.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnSelCheck.Text = "Selector : Check";
            btnSelCheck.TextPadding = new Padding(0, 0, 0, 0);
            btnSelCheck.FontName = "NanumGothic";
            btnSelCheck.FontSize = 12F;
            btnSelCheck.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnSelCheck.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnSelCheck.BackgroundDraw = true;
            btnSelCheck.ButtonColor = null;
            btnSelCheck.ForeColor = null;
            btnSelCheck.BorderColor = null;
            btnSelCheck.Round = null;
            btnSelCheck.Gradient = true;
            btnSelCheck.Clickable = true;
            btnSelCheck.Name = "btnSelCheck";
            btnSelCheck.X = 319F;
            btnSelCheck.Y = 141F;
            btnSelCheck.Width = 142F;
            btnSelCheck.Height = 40F;
            btnSelCheck.Visible = true;
            btnSelCheck.Enabled = true;
            btnSelCheck.Fill = false;
            btnSelCheck.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnInputBox
            btnInputBox.IconString = "";
            btnInputBox.IconSize = 12F;
            btnInputBox.IconGap = 5F;
            btnInputBox.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnInputBox.Text = "InputBox";
            btnInputBox.TextPadding = new Padding(0, 0, 0, 0);
            btnInputBox.FontName = "NanumGothic";
            btnInputBox.FontSize = 12F;
            btnInputBox.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnInputBox.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnInputBox.BackgroundDraw = true;
            btnInputBox.ButtonColor = null;
            btnInputBox.ForeColor = null;
            btnInputBox.BorderColor = null;
            btnInputBox.Round = null;
            btnInputBox.Gradient = true;
            btnInputBox.Clickable = true;
            btnInputBox.Name = "btnInputBox";
            btnInputBox.X = 635F;
            btnInputBox.Y = 3F;
            btnInputBox.Width = 142F;
            btnInputBox.Height = 40F;
            btnInputBox.Visible = true;
            btnInputBox.Enabled = true;
            btnInputBox.Fill = false;
            btnInputBox.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnColorPicker
            btnColorPicker.IconString = "";
            btnColorPicker.IconSize = 12F;
            btnColorPicker.IconGap = 5F;
            btnColorPicker.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnColorPicker.Text = "ColorPickerBox";
            btnColorPicker.TextPadding = new Padding(0, 0, 0, 0);
            btnColorPicker.FontName = "NanumGothic";
            btnColorPicker.FontSize = 12F;
            btnColorPicker.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnColorPicker.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnColorPicker.BackgroundDraw = true;
            btnColorPicker.ButtonColor = null;
            btnColorPicker.ForeColor = null;
            btnColorPicker.BorderColor = null;
            btnColorPicker.Round = null;
            btnColorPicker.Gradient = true;
            btnColorPicker.Clickable = true;
            btnColorPicker.Name = "btnColorPicker";
            btnColorPicker.X = 635F;
            btnColorPicker.Y = 49F;
            btnColorPicker.Width = 142F;
            btnColorPicker.Height = 40F;
            btnColorPicker.Visible = true;
            btnColorPicker.Enabled = true;
            btnColorPicker.Fill = false;
            btnColorPicker.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnTimePicker
            btnTimePicker.IconString = "";
            btnTimePicker.IconSize = 12F;
            btnTimePicker.IconGap = 5F;
            btnTimePicker.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnTimePicker.Text = "DateTimePIckerBox";
            btnTimePicker.TextPadding = new Padding(0, 0, 0, 0);
            btnTimePicker.FontName = "NanumGothic";
            btnTimePicker.FontSize = 12F;
            btnTimePicker.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnTimePicker.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnTimePicker.BackgroundDraw = true;
            btnTimePicker.ButtonColor = null;
            btnTimePicker.ForeColor = null;
            btnTimePicker.BorderColor = null;
            btnTimePicker.Round = null;
            btnTimePicker.Gradient = true;
            btnTimePicker.Clickable = true;
            btnTimePicker.Name = "btnTimePicker";
            btnTimePicker.X = 635F;
            btnTimePicker.Y = 95F;
            btnTimePicker.Width = 142F;
            btnTimePicker.Height = 40F;
            btnTimePicker.Visible = true;
            btnTimePicker.Enabled = true;
            btnTimePicker.Fill = false;
            btnTimePicker.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnMessageOK
            btnMessageOK.IconString = "";
            btnMessageOK.IconSize = 12F;
            btnMessageOK.IconGap = 5F;
            btnMessageOK.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnMessageOK.Text = "Message : OK";
            btnMessageOK.TextPadding = new Padding(0, 0, 0, 0);
            btnMessageOK.FontName = "NanumGothic";
            btnMessageOK.FontSize = 12F;
            btnMessageOK.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnMessageOK.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnMessageOK.BackgroundDraw = true;
            btnMessageOK.ButtonColor = null;
            btnMessageOK.ForeColor = null;
            btnMessageOK.BorderColor = null;
            btnMessageOK.Round = null;
            btnMessageOK.Gradient = true;
            btnMessageOK.Clickable = true;
            btnMessageOK.Name = "btnMessageOK";
            btnMessageOK.X = 477F;
            btnMessageOK.Y = 3F;
            btnMessageOK.Width = 142F;
            btnMessageOK.Height = 40F;
            btnMessageOK.Visible = true;
            btnMessageOK.Enabled = true;
            btnMessageOK.Fill = false;
            btnMessageOK.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region lblKeypad
            lblKeypad.IconString = "";
            lblKeypad.IconSize = 12F;
            lblKeypad.IconGap = 5F;
            lblKeypad.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            lblKeypad.Text = "";
            lblKeypad.TextPadding = new Padding(0, 0, 0, 0);
            lblKeypad.FontName = "NanumGothic";
            lblKeypad.FontSize = 12F;
            lblKeypad.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            lblKeypad.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            lblKeypad.BackgroundDraw = true;
            lblKeypad.LabelColor = null;
            lblKeypad.ForeColor = null;
            lblKeypad.BorderColor = null;
            lblKeypad.Round = null;
            lblKeypad.Name = "lblKeypad";
            lblKeypad.X = 3F;
            lblKeypad.Y = 207F;
            lblKeypad.Width = 142F;
            lblKeypad.Height = 40F;
            lblKeypad.Visible = true;
            lblKeypad.Enabled = true;
            lblKeypad.Fill = false;
            lblKeypad.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region lblKeyboard
            lblKeyboard.IconString = "";
            lblKeyboard.IconSize = 12F;
            lblKeyboard.IconGap = 5F;
            lblKeyboard.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            lblKeyboard.Text = "";
            lblKeyboard.TextPadding = new Padding(0, 0, 0, 0);
            lblKeyboard.FontName = "NanumGothic";
            lblKeyboard.FontSize = 12F;
            lblKeyboard.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            lblKeyboard.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            lblKeyboard.BackgroundDraw = true;
            lblKeyboard.LabelColor = null;
            lblKeyboard.ForeColor = null;
            lblKeyboard.BorderColor = null;
            lblKeyboard.Round = null;
            lblKeyboard.Name = "lblKeyboard";
            lblKeyboard.X = 161F;
            lblKeyboard.Y = 207F;
            lblKeyboard.Width = 142F;
            lblKeyboard.Height = 40F;
            lblKeyboard.Visible = true;
            lblKeyboard.Enabled = true;
            lblKeyboard.Fill = false;
            lblKeyboard.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region lblSelector
            lblSelector.IconString = "";
            lblSelector.IconSize = 12F;
            lblSelector.IconGap = 5F;
            lblSelector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            lblSelector.Text = "";
            lblSelector.TextPadding = new Padding(0, 0, 0, 0);
            lblSelector.FontName = "NanumGothic";
            lblSelector.FontSize = 12F;
            lblSelector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            lblSelector.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            lblSelector.BackgroundDraw = true;
            lblSelector.LabelColor = null;
            lblSelector.ForeColor = null;
            lblSelector.BorderColor = null;
            lblSelector.Round = null;
            lblSelector.Name = "lblSelector";
            lblSelector.X = 319F;
            lblSelector.Y = 207F;
            lblSelector.Width = 142F;
            lblSelector.Height = 40F;
            lblSelector.Visible = true;
            lblSelector.Enabled = true;
            lblSelector.Fill = false;
            lblSelector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region lblOther
            lblOther.IconString = "";
            lblOther.IconSize = 12F;
            lblOther.IconGap = 5F;
            lblOther.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            lblOther.Text = "";
            lblOther.TextPadding = new Padding(0, 0, 0, 0);
            lblOther.FontName = "NanumGothic";
            lblOther.FontSize = 12F;
            lblOther.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            lblOther.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            lblOther.BackgroundDraw = true;
            lblOther.LabelColor = null;
            lblOther.ForeColor = null;
            lblOther.BorderColor = null;
            lblOther.Round = null;
            lblOther.Name = "lblOther";
            lblOther.X = 635F;
            lblOther.Y = 207F;
            lblOther.Width = 142F;
            lblOther.Height = 40F;
            lblOther.Visible = true;
            lblOther.Enabled = true;
            lblOther.Fill = false;
            lblOther.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnMessageOC
            btnMessageOC.IconString = "";
            btnMessageOC.IconSize = 12F;
            btnMessageOC.IconGap = 5F;
            btnMessageOC.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnMessageOC.Text = "Message : O/C";
            btnMessageOC.TextPadding = new Padding(0, 0, 0, 0);
            btnMessageOC.FontName = "NanumGothic";
            btnMessageOC.FontSize = 12F;
            btnMessageOC.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnMessageOC.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnMessageOC.BackgroundDraw = true;
            btnMessageOC.ButtonColor = null;
            btnMessageOC.ForeColor = null;
            btnMessageOC.BorderColor = null;
            btnMessageOC.Round = null;
            btnMessageOC.Gradient = true;
            btnMessageOC.Clickable = true;
            btnMessageOC.Name = "btnMessageOC";
            btnMessageOC.X = 477F;
            btnMessageOC.Y = 49F;
            btnMessageOC.Width = 142F;
            btnMessageOC.Height = 40F;
            btnMessageOC.Visible = true;
            btnMessageOC.Enabled = true;
            btnMessageOC.Fill = false;
            btnMessageOC.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnMessageYN
            btnMessageYN.IconString = "";
            btnMessageYN.IconSize = 12F;
            btnMessageYN.IconGap = 5F;
            btnMessageYN.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnMessageYN.Text = "Message : Y/N";
            btnMessageYN.TextPadding = new Padding(0, 0, 0, 0);
            btnMessageYN.FontName = "NanumGothic";
            btnMessageYN.FontSize = 12F;
            btnMessageYN.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnMessageYN.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnMessageYN.BackgroundDraw = true;
            btnMessageYN.ButtonColor = null;
            btnMessageYN.ForeColor = null;
            btnMessageYN.BorderColor = null;
            btnMessageYN.Round = null;
            btnMessageYN.Gradient = true;
            btnMessageYN.Clickable = true;
            btnMessageYN.Name = "btnMessageYN";
            btnMessageYN.X = 477F;
            btnMessageYN.Y = 95F;
            btnMessageYN.Width = 142F;
            btnMessageYN.Height = 40F;
            btnMessageYN.Visible = true;
            btnMessageYN.Enabled = true;
            btnMessageYN.Fill = false;
            btnMessageYN.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnMessageYNC
            btnMessageYNC.IconString = "";
            btnMessageYNC.IconSize = 12F;
            btnMessageYNC.IconGap = 5F;
            btnMessageYNC.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnMessageYNC.Text = "Message : Y/N/C";
            btnMessageYNC.TextPadding = new Padding(0, 0, 0, 0);
            btnMessageYNC.FontName = "NanumGothic";
            btnMessageYNC.FontSize = 12F;
            btnMessageYNC.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnMessageYNC.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnMessageYNC.BackgroundDraw = true;
            btnMessageYNC.ButtonColor = null;
            btnMessageYNC.ForeColor = null;
            btnMessageYNC.BorderColor = null;
            btnMessageYNC.Round = null;
            btnMessageYNC.Gradient = true;
            btnMessageYNC.Clickable = true;
            btnMessageYNC.Name = "btnMessageYNC";
            btnMessageYNC.X = 477F;
            btnMessageYNC.Y = 141F;
            btnMessageYNC.Width = 142F;
            btnMessageYNC.Height = 40F;
            btnMessageYNC.Visible = true;
            btnMessageYNC.Enabled = true;
            btnMessageYNC.Fill = false;
            btnMessageYNC.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region lblMessage
            lblMessage.IconString = "";
            lblMessage.IconSize = 12F;
            lblMessage.IconGap = 5F;
            lblMessage.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            lblMessage.Text = "";
            lblMessage.TextPadding = new Padding(0, 0, 0, 0);
            lblMessage.FontName = "NanumGothic";
            lblMessage.FontSize = 12F;
            lblMessage.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            lblMessage.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            lblMessage.BackgroundDraw = true;
            lblMessage.LabelColor = null;
            lblMessage.ForeColor = null;
            lblMessage.BorderColor = null;
            lblMessage.Round = null;
            lblMessage.Name = "lblMessage";
            lblMessage.X = 477F;
            lblMessage.Y = 207F;
            lblMessage.Width = 142F;
            lblMessage.Height = 40F;
            lblMessage.Visible = true;
            lblMessage.Enabled = true;
            lblMessage.Fill = false;
            lblMessage.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region btnCustomWindow
            btnCustomWindow.IconString = "";
            btnCustomWindow.IconSize = 12F;
            btnCustomWindow.IconGap = 5F;
            btnCustomWindow.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            btnCustomWindow.Text = "Custom Window";
            btnCustomWindow.TextPadding = new Padding(0, 0, 0, 0);
            btnCustomWindow.FontName = "NanumGothic";
            btnCustomWindow.FontSize = 12F;
            btnCustomWindow.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            btnCustomWindow.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            btnCustomWindow.BackgroundDraw = true;
            btnCustomWindow.ButtonColor = null;
            btnCustomWindow.ForeColor = null;
            btnCustomWindow.BorderColor = null;
            btnCustomWindow.Round = null;
            btnCustomWindow.Gradient = true;
            btnCustomWindow.Clickable = true;
            btnCustomWindow.Name = "btnCustomWindow";
            btnCustomWindow.X = 635F;
            btnCustomWindow.Y = 141F;
            btnCustomWindow.Width = 142F;
            btnCustomWindow.Height = 40F;
            btnCustomWindow.Visible = true;
            btnCustomWindow.Enabled = true;
            btnCustomWindow.Fill = false;
            btnCustomWindow.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region dvLabel1
            dvLabel1.IconString = "";
            dvLabel1.IconSize = 12F;
            dvLabel1.IconGap = 5F;
            dvLabel1.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            dvLabel1.Text = "Flat Label";
            dvLabel1.TextPadding = new Padding(0, 0, 0, 0);
            dvLabel1.FontName = "NanumGothic";
            dvLabel1.FontSize = 12F;
            dvLabel1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            dvLabel1.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            dvLabel1.BackgroundDraw = true;
            dvLabel1.LabelColor = null;
            dvLabel1.ForeColor = null;
            dvLabel1.BorderColor = null;
            dvLabel1.Round = null;
            dvLabel1.Name = "dvLabel1";
            dvLabel1.X = 130F;
            dvLabel1.Y = 13F;
            dvLabel1.Width = 111.000015F;
            dvLabel1.Height = 34F;
            dvLabel1.Visible = true;
            dvLabel1.Enabled = true;
            dvLabel1.Fill = false;
            dvLabel1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #endregion

            #region add
            Controls.Add(dvTableLayoutPanel1);
            dvTableLayoutPanel1.Controls.Add(btnKeypadInt, 0, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeypadFloat, 0, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeypadPasswd, 0, 2, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeypadHex, 0, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeyboardKor, 2, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeyboardEng, 2, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeyboardNum, 2, 2, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnKeyboardEngOnly, 2, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnSelSelector, 4, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnSelWheel, 4, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnSelRadio, 4, 2, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnSelCheck, 4, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnInputBox, 8, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnColorPicker, 8, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnTimePicker, 8, 2, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnMessageOK, 6, 0, 1, 1);
            dvTableLayoutPanel1.Controls.Add(lblKeypad, 0, 5, 1, 1);
            dvTableLayoutPanel1.Controls.Add(lblKeyboard, 2, 5, 1, 1);
            dvTableLayoutPanel1.Controls.Add(lblSelector, 4, 5, 1, 1);
            dvTableLayoutPanel1.Controls.Add(lblOther, 8, 5, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnMessageOC, 6, 1, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnMessageYN, 6, 2, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnMessageYNC, 6, 3, 1, 1);
            dvTableLayoutPanel1.Controls.Add(lblMessage, 6, 5, 1, 1);
            dvTableLayoutPanel1.Controls.Add(btnCustomWindow, 8, 3, 1, 1);
            Controls.Add(dvLabel1);
            #endregion
        }
    }
}
