using System;
using Devinno.Skia.Utils;
using Devinno.Skia.Controls;
using Devinno.Skia.Containers;
using Devinno.Skia.Design;

namespace SampleRPi.Pages
{
    partial class PageInput
    {
        #region declare
        private DvTableLayoutPanel tbl;
        private DvInputText inText;
        private DvInputNumber<Int32> inInt;
        private DvInputBool inBool;
        private DvInputSelector inSelector;
        private DvSelector selector;
        private DvValueInputText vinText;
        private DvValueInputNumber<Int32> vinInt;
        private DvValueInputSelector vinSelector;
        private DvValueInputBool vinBool;
        private DvValueInputCombo vinCombo;
        private DvValueInputNumber<Int32> vinTest1;
        private DvValueInputNumber<Int32> vinTest2;
        private DvOnOff oo1;
        private DvCalendar calendar;
        private DvNumberbox nb1;
        private DvNumberbox nb2;
        private DvNumberbox nb3;
        private DvOnOff oo2;
        private DvOnOff oo3;
        private DvOnOff oo4;
        private DvSwitch sw1;
        private DvSwitch sw2;
        private DvSwitch sw3;
        private DvSwitch sw4;
        #endregion

        public void InitializeComponent()
        {
            #region base
            UseMasterPage = true;
            BackgroundDraw = false;
            BackColor = null;
            BackgroundImage = null;
            AnimationType = null;
            Text = "Input";
            IconString = "";
            #endregion

            #region new
            tbl = new DvTableLayoutPanel { Name = nameof(tbl) };
            inText = new DvInputText { Name = nameof(inText) };
            inInt = new DvInputNumber<Int32> { Name = nameof(inInt) };
            inBool = new DvInputBool { Name = nameof(inBool) };
            inSelector = new DvInputSelector { Name = nameof(inSelector) };
            selector = new DvSelector { Name = nameof(selector) };
            vinText = new DvValueInputText { Name = nameof(vinText) };
            vinInt = new DvValueInputNumber<Int32> { Name = nameof(vinInt) };
            vinSelector = new DvValueInputSelector { Name = nameof(vinSelector) };
            vinBool = new DvValueInputBool { Name = nameof(vinBool) };
            vinCombo = new DvValueInputCombo { Name = nameof(vinCombo) };
            vinTest1 = new DvValueInputNumber<Int32> { Name = nameof(vinTest1) };
            vinTest2 = new DvValueInputNumber<Int32> { Name = nameof(vinTest2) };
            oo1 = new DvOnOff { Name = nameof(oo1) };
            calendar = new DvCalendar { Name = nameof(calendar) };
            nb1 = new DvNumberbox { Name = nameof(nb1) };
            nb2 = new DvNumberbox { Name = nameof(nb2) };
            nb3 = new DvNumberbox { Name = nameof(nb3) };
            oo2 = new DvOnOff { Name = nameof(oo2) };
            oo3 = new DvOnOff { Name = nameof(oo3) };
            oo4 = new DvOnOff { Name = nameof(oo4) };
            sw1 = new DvSwitch { Name = nameof(sw1) };
            sw2 = new DvSwitch { Name = nameof(sw2) };
            sw3 = new DvSwitch { Name = nameof(sw3) };
            sw4 = new DvSwitch { Name = nameof(sw4) };
            #endregion

            #region controls
            #region tbl
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 120F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 130F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 250F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            tbl.Columns.Add(new SizeInfo(DvSizeMode.Percent, 100F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 40F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Pixel, 10F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Rows.Add(new SizeInfo(DvSizeMode.Percent, 25F));
            tbl.Name = "tbl";
            tbl.X = 10F;
            tbl.Y = 60F;
            tbl.Width = 780F;
            tbl.Height = 410F;
            tbl.Visible = true;
            tbl.Enabled = true;
            tbl.Fill = true;
            tbl.Margin = new Padding(10, 60, 10, 10);
            #endregion
            #region inText
            inText.Value = "";
            inText.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            inText.FontName = "NanumGothic";
            inText.FontSize = 12F;
            inText.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inText.KeyboardWidth = 600;
            inText.KeyboardHeight = 400;
            inText.BackgroundDraw = true;
            inText.InputColor = null;
            inText.ForeColor = null;
            inText.BorderColor = null;
            inText.Round = null;
            inText.Name = "inText";
            inText.X = 3F;
            inText.Y = 3F;
            inText.Width = 244F;
            inText.Height = 34F;
            inText.Visible = true;
            inText.Enabled = true;
            inText.Fill = false;
            inText.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region inInt
            inInt.Value = 0;
            inInt.Minimum = null;
            inInt.Maximum = null;
            inInt.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            inInt.FormatString = "";
            inInt.FontName = "NanumGothic";
            inInt.FontSize = 12F;
            inInt.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inInt.KeypadWidth = 300;
            inInt.KeypadHeight = 400;
            inInt.BackgroundDraw = true;
            inInt.InputColor = null;
            inInt.ForeColor = null;
            inInt.BorderColor = null;
            inInt.Round = null;
            inInt.Name = "inInt";
            inInt.X = 3F;
            inInt.Y = 43F;
            inInt.Width = 244F;
            inInt.Height = 34F;
            inInt.Visible = true;
            inInt.Enabled = true;
            inInt.Fill = false;
            inInt.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region inBool
            inBool.Value = false;
            inBool.OnText = "ON";
            inBool.OffText = "OFF";
            inBool.FontName = "NanumGothic";
            inBool.FontSize = 12F;
            inBool.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inBool.BackgroundDraw = true;
            inBool.InputColor = null;
            inBool.ForeColor = null;
            inBool.BorderColor = null;
            inBool.Round = null;
            inBool.Name = "inBool";
            inBool.X = 3F;
            inBool.Y = 83F;
            inBool.Width = 244F;
            inBool.Height = 34F;
            inBool.Visible = true;
            inBool.Enabled = true;
            inBool.Fill = false;
            inBool.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region inSelector
            inSelector.FontName = "NanumGothic";
            inSelector.FontSize = 12F;
            inSelector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            inSelector.IconSize = 12F;
            inSelector.IconGap = 5F;
            inSelector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            inSelector.SelectedIndex = -1;
            inSelector.BackgroundDraw = true;
            inSelector.InputColor = null;
            inSelector.ForeColor = null;
            inSelector.BorderColor = null;
            inSelector.Round = null;
            inSelector.Name = "inSelector";
            inSelector.X = 3F;
            inSelector.Y = 123F;
            inSelector.Width = 244F;
            inSelector.Height = 34F;
            inSelector.Visible = true;
            inSelector.Enabled = true;
            inSelector.Fill = false;
            inSelector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region selector
            selector.SelectorColor = null;
            selector.ForeColor = null;
            selector.BackgroundDraw = true;
            selector.ButtonSize = null;
            selector.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            selector.Round = null;
            selector.FontName = "NanumGothic";
            selector.FontSize = 12F;
            selector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            selector.IconSize = 12F;
            selector.IconGap = 5F;
            selector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            selector.SelectedIndex = -1;
            selector.Name = "selector";
            selector.X = 3F;
            selector.Y = 163F;
            selector.Width = 244F;
            selector.Height = 34F;
            selector.Visible = true;
            selector.Enabled = true;
            selector.Fill = false;
            selector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinText
            vinText.Value = "";
            vinText.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            vinText.FontName = "NanumGothic";
            vinText.FontSize = 12F;
            vinText.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinText.KeyboardWidth = 600;
            vinText.KeyboardHeight = 400;
            vinText.KeyboardMode = Devinno.Skia.Dialogs.KeyboardMode.English;
            vinText.TitleIconString = "";
            vinText.TitleIconSize = 12F;
            vinText.TitleIconGap = 5F;
            vinText.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinText.Title = "Text";
            vinText.TitleFontName = "NanumGothic";
            vinText.TitleFontSize = 12F;
            vinText.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinText.TitleAreaSize = 80F;
            vinText.ButtonAreaSize = null;
            vinText.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinText.BackgroundDraw = true;
            vinText.TitleColor = null;
            vinText.InputColor = null;
            vinText.ButtonColor = null;
            vinText.BorderColor = null;
            vinText.ForeColor = null;
            vinText.Round = null;
            vinText.Name = "vinText";
            vinText.X = 263F;
            vinText.Y = 3F;
            vinText.Width = 244F;
            vinText.Height = 34F;
            vinText.Visible = true;
            vinText.Enabled = true;
            vinText.Fill = false;
            vinText.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinInt
            vinInt.Value = 0;
            vinInt.Minimum = null;
            vinInt.Maximum = null;
            vinInt.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            vinInt.FormatString = "";
            vinInt.FontName = "NanumGothic";
            vinInt.FontSize = 12F;
            vinInt.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinInt.KeypadWidth = 300;
            vinInt.KeypadHeight = 400;
            vinInt.TitleIconString = "";
            vinInt.TitleIconSize = 12F;
            vinInt.TitleIconGap = 5F;
            vinInt.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinInt.Title = "Int";
            vinInt.TitleFontName = "NanumGothic";
            vinInt.TitleFontSize = 12F;
            vinInt.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinInt.TitleAreaSize = 80F;
            vinInt.ButtonAreaSize = null;
            vinInt.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinInt.BackgroundDraw = true;
            vinInt.TitleColor = null;
            vinInt.InputColor = null;
            vinInt.ButtonColor = null;
            vinInt.BorderColor = null;
            vinInt.ForeColor = null;
            vinInt.Round = null;
            vinInt.Name = "vinInt";
            vinInt.X = 263F;
            vinInt.Y = 43F;
            vinInt.Width = 244F;
            vinInt.Height = 34F;
            vinInt.Visible = true;
            vinInt.Enabled = true;
            vinInt.Fill = false;
            vinInt.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinSelector
            vinSelector.FontName = "NanumGothic";
            vinSelector.FontSize = 12F;
            vinSelector.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinSelector.IconSize = 12F;
            vinSelector.IconGap = 5F;
            vinSelector.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinSelector.SelectedIndex = -1;
            vinSelector.TitleIconString = "";
            vinSelector.TitleIconSize = 12F;
            vinSelector.TitleIconGap = 5F;
            vinSelector.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinSelector.Title = "Selector";
            vinSelector.TitleFontName = "NanumGothic";
            vinSelector.TitleFontSize = 12F;
            vinSelector.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinSelector.TitleAreaSize = 80F;
            vinSelector.ButtonAreaSize = null;
            vinSelector.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinSelector.BackgroundDraw = true;
            vinSelector.TitleColor = null;
            vinSelector.InputColor = null;
            vinSelector.ButtonColor = null;
            vinSelector.BorderColor = null;
            vinSelector.ForeColor = null;
            vinSelector.Round = null;
            vinSelector.Name = "vinSelector";
            vinSelector.X = 263F;
            vinSelector.Y = 123F;
            vinSelector.Width = 244F;
            vinSelector.Height = 34F;
            vinSelector.Visible = true;
            vinSelector.Enabled = true;
            vinSelector.Fill = false;
            vinSelector.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinBool
            vinBool.Value = false;
            vinBool.OnText = "ON";
            vinBool.OffText = "OFF";
            vinBool.FontName = "NanumGothic";
            vinBool.FontSize = 12F;
            vinBool.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinBool.TitleIconString = "";
            vinBool.TitleIconSize = 12F;
            vinBool.TitleIconGap = 5F;
            vinBool.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinBool.Title = "Bool";
            vinBool.TitleFontName = "NanumGothic";
            vinBool.TitleFontSize = 12F;
            vinBool.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinBool.TitleAreaSize = 80F;
            vinBool.ButtonAreaSize = null;
            vinBool.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinBool.BackgroundDraw = true;
            vinBool.TitleColor = null;
            vinBool.InputColor = null;
            vinBool.ButtonColor = null;
            vinBool.BorderColor = null;
            vinBool.ForeColor = null;
            vinBool.Round = null;
            vinBool.Name = "vinBool";
            vinBool.X = 263F;
            vinBool.Y = 83F;
            vinBool.Width = 244F;
            vinBool.Height = 34F;
            vinBool.Visible = true;
            vinBool.Enabled = true;
            vinBool.Fill = false;
            vinBool.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinCombo
            vinCombo.FontName = "NanumGothic";
            vinCombo.FontSize = 12F;
            vinCombo.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinCombo.IconSize = 12F;
            vinCombo.IconGap = 5F;
            vinCombo.IconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinCombo.SelectedIndex = -1;
            vinCombo.MaximumViewCount = 8;
            vinCombo.ItemHeight = 30;
            vinCombo.TitleIconString = "";
            vinCombo.TitleIconSize = 12F;
            vinCombo.TitleIconGap = 5F;
            vinCombo.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinCombo.Title = "Combbo";
            vinCombo.TitleFontName = "NanumGothic";
            vinCombo.TitleFontSize = 12F;
            vinCombo.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinCombo.TitleAreaSize = 80F;
            vinCombo.ButtonAreaSize = null;
            vinCombo.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinCombo.BackgroundDraw = true;
            vinCombo.TitleColor = null;
            vinCombo.InputColor = null;
            vinCombo.ButtonColor = null;
            vinCombo.BorderColor = null;
            vinCombo.ForeColor = null;
            vinCombo.Round = null;
            vinCombo.Name = "vinCombo";
            vinCombo.X = 263F;
            vinCombo.Y = 163F;
            vinCombo.Width = 244F;
            vinCombo.Height = 34F;
            vinCombo.Visible = true;
            vinCombo.Enabled = true;
            vinCombo.Fill = false;
            vinCombo.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinTest1
            vinTest1.Value = 0;
            vinTest1.Minimum = null;
            vinTest1.Maximum = null;
            vinTest1.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            vinTest1.FormatString = "";
            vinTest1.FontName = "NanumGothic";
            vinTest1.FontSize = 12F;
            vinTest1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinTest1.KeypadWidth = 300;
            vinTest1.KeypadHeight = 400;
            vinTest1.TitleIconString = "";
            vinTest1.TitleIconSize = 12F;
            vinTest1.TitleIconGap = 5F;
            vinTest1.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinTest1.Title = "Test";
            vinTest1.TitleFontName = "NanumGothic";
            vinTest1.TitleFontSize = 12F;
            vinTest1.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinTest1.TitleAreaSize = 80F;
            vinTest1.Buttons.Add(new ButtonInfo("") { Size = new SizeInfo(DvSizeMode.Percent, 100F), IconString = "fa-play", IconSize = 18, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            vinTest1.ButtonAreaSize = 40F;
            vinTest1.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            vinTest1.BackgroundDraw = true;
            vinTest1.TitleColor = null;
            vinTest1.InputColor = null;
            vinTest1.ButtonColor = null;
            vinTest1.BorderColor = null;
            vinTest1.ForeColor = null;
            vinTest1.Round = null;
            vinTest1.Name = "vinTest1";
            vinTest1.X = 263F;
            vinTest1.Y = 213F;
            vinTest1.Width = 244F;
            vinTest1.Height = 44F;
            vinTest1.Visible = true;
            vinTest1.Enabled = true;
            vinTest1.Fill = false;
            vinTest1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region vinTest2
            vinTest2.Value = 0;
            vinTest2.Minimum = null;
            vinTest2.Maximum = null;
            vinTest2.ContentAlignment = Devinno.Skia.Design.DvContentAlignment.MiddleCenter;
            vinTest2.FormatString = "";
            vinTest2.FontName = "NanumGothic";
            vinTest2.FontSize = 12F;
            vinTest2.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinTest2.KeypadWidth = 300;
            vinTest2.KeypadHeight = 400;
            vinTest2.TitleIconString = "";
            vinTest2.TitleIconSize = 12F;
            vinTest2.TitleIconGap = 5F;
            vinTest2.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            vinTest2.Title = "Test 2";
            vinTest2.TitleFontName = "NanumGothic";
            vinTest2.TitleFontSize = 12F;
            vinTest2.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            vinTest2.TitleAreaSize = 30F;
            vinTest2.Buttons.Add(new ButtonInfo("") { Size = new SizeInfo(DvSizeMode.Percent, 33F), IconString = "fa-chevron-left", IconSize = 18, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            vinTest2.Buttons.Add(new ButtonInfo("") { Size = new SizeInfo(DvSizeMode.Percent, 34F), IconString = "fa-stop", IconSize = 18, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            vinTest2.Buttons.Add(new ButtonInfo("") { Size = new SizeInfo(DvSizeMode.Percent, 33F), IconString = "fa-chevron-right", IconSize = 18, IconAlignment = DvTextIconAlignment.LeftRight, IconGap = 5, Text = "", FontName = "NanumGothic", FontSize = 12, FontStyle = DvFontStyle.Normal, TextPadding = new Padding(0, 0, 0, 0) });
            vinTest2.ButtonAreaSize = 40F;
            vinTest2.Direction = Devinno.Skia.Design.DvDirectionHV.Vertical;
            vinTest2.BackgroundDraw = true;
            vinTest2.TitleColor = null;
            vinTest2.InputColor = null;
            vinTest2.ButtonColor = null;
            vinTest2.BorderColor = null;
            vinTest2.ForeColor = null;
            vinTest2.Round = null;
            vinTest2.Name = "vinTest2";
            vinTest2.X = 263F;
            vinTest2.Y = 263F;
            vinTest2.Width = 244F;
            vinTest2.Height = 144F;
            vinTest2.Visible = true;
            vinTest2.Enabled = true;
            vinTest2.Fill = false;
            vinTest2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo1
            oo1.CursorColor = null;
            oo1.OnBoxColor = null;
            oo1.OffBoxColor = null;
            oo1.OnTextColor = null;
            oo1.OffTextColor = null;
            oo1.OnText = "ON";
            oo1.OffText = "OFF";
            oo1.FontName = "NanumGothic";
            oo1.FontSize = 12F;
            oo1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo1.CursorPadding = 5F;
            oo1.OnOff = false;
            oo1.Name = "oo1";
            oo1.X = 3F;
            oo1.Y = 213F;
            oo1.Width = 114F;
            oo1.Height = 44F;
            oo1.Visible = true;
            oo1.Enabled = true;
            oo1.Fill = false;
            oo1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region calendar
            calendar.ForeColor = null;
            calendar.BoxColor = null;
            calendar.SelectColor = null;
            calendar.MultiSelect = false;
            calendar.NoneSelect = false;
            calendar.BackgroundDraw = true;
            calendar.FontName = "NanumGothic";
            calendar.FontSize = 12F;
            calendar.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            calendar.Name = "calendar";
            calendar.X = 523F;
            calendar.Y = 3F;
            calendar.Width = 254F;
            calendar.Height = 194F;
            calendar.Visible = true;
            calendar.Enabled = true;
            calendar.Fill = false;
            calendar.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region nb1
            nb1.Value = 0;
            nb1.Minimum = 0;
            nb1.Maximum = 100;
            nb1.Tick = 1;
            nb1.FormatString = "";
            nb1.FontName = "NanumGothic";
            nb1.FontSize = 12F;
            nb1.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb1.ButtonIconSize = 14;
            nb1.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            nb1.TitleIconString = "";
            nb1.TitleIconSize = 12F;
            nb1.TitleIconGap = 5F;
            nb1.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            nb1.Title = "";
            nb1.TitleFontName = "NanumGothic";
            nb1.TitleFontSize = 12F;
            nb1.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb1.TitleAreaSize = null;
            nb1.ButtonAreaSize = 88F;
            nb1.BackgroundDraw = true;
            nb1.TitleColor = null;
            nb1.ValueColor = null;
            nb1.ButtonColor = null;
            nb1.BorderColor = null;
            nb1.ForeColor = null;
            nb1.Round = null;
            nb1.Name = "nb1";
            nb1.X = 523F;
            nb1.Y = 213F;
            nb1.Width = 254F;
            nb1.Height = 44F;
            nb1.Visible = true;
            nb1.Enabled = true;
            nb1.Fill = false;
            nb1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region nb2
            nb2.Value = 0;
            nb2.Minimum = 0;
            nb2.Maximum = 100;
            nb2.Tick = 1;
            nb2.FormatString = "";
            nb2.FontName = "NanumGothic";
            nb2.FontSize = 12F;
            nb2.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb2.ButtonIconSize = 14;
            nb2.Direction = Devinno.Skia.Design.DvDirectionHV.Horizon;
            nb2.TitleIconString = "";
            nb2.TitleIconSize = 12F;
            nb2.TitleIconGap = 5F;
            nb2.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            nb2.Title = "Num 2";
            nb2.TitleFontName = "NanumGothic";
            nb2.TitleFontSize = 12F;
            nb2.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb2.TitleAreaSize = 70F;
            nb2.ButtonAreaSize = 88F;
            nb2.BackgroundDraw = true;
            nb2.TitleColor = null;
            nb2.ValueColor = null;
            nb2.ButtonColor = null;
            nb2.BorderColor = null;
            nb2.ForeColor = null;
            nb2.Round = null;
            nb2.Name = "nb2";
            nb2.X = 523F;
            nb2.Y = 263F;
            nb2.Width = 254F;
            nb2.Height = 44F;
            nb2.Visible = true;
            nb2.Enabled = true;
            nb2.Fill = false;
            nb2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region nb3
            nb3.Value = 0;
            nb3.Minimum = 0;
            nb3.Maximum = 100;
            nb3.Tick = 1;
            nb3.FormatString = "";
            nb3.FontName = "NanumGothic";
            nb3.FontSize = 12F;
            nb3.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb3.ButtonIconSize = 14;
            nb3.Direction = Devinno.Skia.Design.DvDirectionHV.Vertical;
            nb3.TitleIconString = "";
            nb3.TitleIconSize = 12F;
            nb3.TitleIconGap = 5F;
            nb3.TitleIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            nb3.Title = "Num 3";
            nb3.TitleFontName = "NanumGothic";
            nb3.TitleFontSize = 12F;
            nb3.TitleFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            nb3.TitleAreaSize = 30F;
            nb3.ButtonAreaSize = 31.333334F;
            nb3.BackgroundDraw = true;
            nb3.TitleColor = null;
            nb3.ValueColor = null;
            nb3.ButtonColor = null;
            nb3.BorderColor = null;
            nb3.ForeColor = null;
            nb3.Round = null;
            nb3.Name = "nb3";
            nb3.X = 523F;
            nb3.Y = 313F;
            nb3.Width = 254F;
            nb3.Height = 94F;
            nb3.Visible = true;
            nb3.Enabled = true;
            nb3.Fill = false;
            nb3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo2
            oo2.CursorColor = null;
            oo2.OnBoxColor = Util.FromArgb(255, 0, 128, 0);
            oo2.OffBoxColor = null;
            oo2.OnTextColor = null;
            oo2.OffTextColor = null;
            oo2.OnText = "ON";
            oo2.OffText = "OFF";
            oo2.FontName = "NanumGothic";
            oo2.FontSize = 12F;
            oo2.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo2.CursorPadding = 5F;
            oo2.OnOff = false;
            oo2.Name = "oo2";
            oo2.X = 3F;
            oo2.Y = 263F;
            oo2.Width = 114F;
            oo2.Height = 44F;
            oo2.Visible = true;
            oo2.Enabled = true;
            oo2.Fill = false;
            oo2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo3
            oo3.CursorColor = null;
            oo3.OnBoxColor = Util.FromArgb(255, 0, 0, 255);
            oo3.OffBoxColor = null;
            oo3.OnTextColor = null;
            oo3.OffTextColor = null;
            oo3.OnText = "ON";
            oo3.OffText = "OFF";
            oo3.FontName = "NanumGothic";
            oo3.FontSize = 12F;
            oo3.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo3.CursorPadding = 5F;
            oo3.OnOff = false;
            oo3.Name = "oo3";
            oo3.X = 3F;
            oo3.Y = 313F;
            oo3.Width = 114F;
            oo3.Height = 44F;
            oo3.Visible = true;
            oo3.Enabled = true;
            oo3.Fill = false;
            oo3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region oo4
            oo4.CursorColor = null;
            oo4.OnBoxColor = Util.FromArgb(255, 90, 90, 90);
            oo4.OffBoxColor = null;
            oo4.OnTextColor = null;
            oo4.OffTextColor = null;
            oo4.OnText = "ON";
            oo4.OffText = "OFF";
            oo4.FontName = "NanumGothic";
            oo4.FontSize = 12F;
            oo4.FontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            oo4.CursorPadding = 5F;
            oo4.OnOff = false;
            oo4.Name = "oo4";
            oo4.X = 3F;
            oo4.Y = 363F;
            oo4.Width = 114F;
            oo4.Height = 44F;
            oo4.Visible = true;
            oo4.Enabled = true;
            oo4.Fill = false;
            oo4.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw1
            sw1.OnBoxColor = null;
            sw1.OffBoxColor = null;
            sw1.SwitchColor = null;
            sw1.ForeColor = null;
            sw1.OnIconString = "";
            sw1.OnIconSize = 12F;
            sw1.OnIconGap = 5F;
            sw1.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw1.OnText = "ON";
            sw1.OnTextPadding = new Padding(0, 0, 0, 0);
            sw1.OnFontName = "NanumGothic";
            sw1.OnFontSize = 12F;
            sw1.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw1.OffIconString = "";
            sw1.OffIconSize = 12F;
            sw1.OffIconGap = 5F;
            sw1.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw1.OffText = "OFF";
            sw1.OffTextPadding = new Padding(0, 0, 0, 0);
            sw1.OffFontName = "NanumGothic";
            sw1.OffFontSize = 12F;
            sw1.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw1.Corner = null;
            sw1.SwitchPadding = 5F;
            sw1.OnOff = false;
            sw1.Name = "sw1";
            sw1.X = 123F;
            sw1.Y = 213F;
            sw1.Width = 124F;
            sw1.Height = 44F;
            sw1.Visible = true;
            sw1.Enabled = true;
            sw1.Fill = false;
            sw1.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw2
            sw2.OnBoxColor = Util.FromArgb(255, 0, 128, 0);
            sw2.OffBoxColor = null;
            sw2.SwitchColor = null;
            sw2.ForeColor = null;
            sw2.OnIconString = "";
            sw2.OnIconSize = 12F;
            sw2.OnIconGap = 5F;
            sw2.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw2.OnText = "ON";
            sw2.OnTextPadding = new Padding(0, 0, 0, 0);
            sw2.OnFontName = "NanumGothic";
            sw2.OnFontSize = 12F;
            sw2.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw2.OffIconString = "";
            sw2.OffIconSize = 12F;
            sw2.OffIconGap = 5F;
            sw2.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw2.OffText = "OFF";
            sw2.OffTextPadding = new Padding(0, 0, 0, 0);
            sw2.OffFontName = "NanumGothic";
            sw2.OffFontSize = 12F;
            sw2.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw2.Corner = null;
            sw2.SwitchPadding = 5F;
            sw2.OnOff = false;
            sw2.Name = "sw2";
            sw2.X = 123F;
            sw2.Y = 263F;
            sw2.Width = 124F;
            sw2.Height = 44F;
            sw2.Visible = true;
            sw2.Enabled = true;
            sw2.Fill = false;
            sw2.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw3
            sw3.OnBoxColor = Util.FromArgb(255, 0, 0, 255);
            sw3.OffBoxColor = null;
            sw3.SwitchColor = null;
            sw3.ForeColor = null;
            sw3.OnIconString = "";
            sw3.OnIconSize = 12F;
            sw3.OnIconGap = 5F;
            sw3.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw3.OnText = "ON";
            sw3.OnTextPadding = new Padding(0, 0, 0, 0);
            sw3.OnFontName = "NanumGothic";
            sw3.OnFontSize = 12F;
            sw3.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw3.OffIconString = "";
            sw3.OffIconSize = 12F;
            sw3.OffIconGap = 5F;
            sw3.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw3.OffText = "OFF";
            sw3.OffTextPadding = new Padding(0, 0, 0, 0);
            sw3.OffFontName = "NanumGothic";
            sw3.OffFontSize = 12F;
            sw3.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw3.Corner = null;
            sw3.SwitchPadding = 5F;
            sw3.OnOff = false;
            sw3.Name = "sw3";
            sw3.X = 123F;
            sw3.Y = 313F;
            sw3.Width = 124F;
            sw3.Height = 44F;
            sw3.Visible = true;
            sw3.Enabled = true;
            sw3.Fill = false;
            sw3.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #region sw4
            sw4.OnBoxColor = Util.FromArgb(255, 90, 90, 90);
            sw4.OffBoxColor = null;
            sw4.SwitchColor = null;
            sw4.ForeColor = null;
            sw4.OnIconString = "";
            sw4.OnIconSize = 12F;
            sw4.OnIconGap = 5F;
            sw4.OnIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw4.OnText = "ON";
            sw4.OnTextPadding = new Padding(0, 0, 0, 0);
            sw4.OnFontName = "NanumGothic";
            sw4.OnFontSize = 12F;
            sw4.OnFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw4.OffIconString = "";
            sw4.OffIconSize = 12F;
            sw4.OffIconGap = 5F;
            sw4.OffIconAlignment = Devinno.Skia.Design.DvTextIconAlignment.LeftRight;
            sw4.OffText = "OFF";
            sw4.OffTextPadding = new Padding(0, 0, 0, 0);
            sw4.OffFontName = "NanumGothic";
            sw4.OffFontSize = 12F;
            sw4.OffFontStyle = Devinno.Skia.Design.DvFontStyle.Normal;
            sw4.Corner = null;
            sw4.SwitchPadding = 5F;
            sw4.OnOff = false;
            sw4.Name = "sw4";
            sw4.X = 123F;
            sw4.Y = 363F;
            sw4.Width = 124F;
            sw4.Height = 44F;
            sw4.Visible = true;
            sw4.Enabled = true;
            sw4.Fill = false;
            sw4.Margin = new Padding(3, 3, 3, 3);
            #endregion
            #endregion

            #region add
            this.Controls.Add(tbl);
            tbl.Controls.Add(inText, 0, 0, 2, 1);
            tbl.Controls.Add(inInt, 0, 1, 2, 1);
            tbl.Controls.Add(inBool, 0, 2, 2, 1);
            tbl.Controls.Add(inSelector, 0, 3, 2, 1);
            tbl.Controls.Add(selector, 0, 4, 2, 1);
            tbl.Controls.Add(vinText, 3, 0, 1, 1);
            tbl.Controls.Add(vinInt, 3, 1, 1, 1);
            tbl.Controls.Add(vinSelector, 3, 3, 1, 1);
            tbl.Controls.Add(vinBool, 3, 2, 1, 1);
            tbl.Controls.Add(vinCombo, 3, 4, 1, 1);
            tbl.Controls.Add(vinTest1, 3, 6, 1, 1);
            tbl.Controls.Add(vinTest2, 3, 7, 1, 3);
            tbl.Controls.Add(oo1, 0, 6, 1, 1);
            tbl.Controls.Add(calendar, 5, 0, 1, 5);
            tbl.Controls.Add(nb1, 5, 6, 1, 1);
            tbl.Controls.Add(nb2, 5, 7, 1, 1);
            tbl.Controls.Add(nb3, 5, 8, 1, 2);
            tbl.Controls.Add(oo2, 0, 7, 1, 1);
            tbl.Controls.Add(oo3, 0, 8, 1, 1);
            tbl.Controls.Add(oo4, 0, 9, 1, 1);
            tbl.Controls.Add(sw1, 1, 6, 1, 1);
            tbl.Controls.Add(sw2, 1, 7, 1, 1);
            tbl.Controls.Add(sw3, 1, 8, 1, 1);
            tbl.Controls.Add(sw4, 1, 9, 1, 1);
            #endregion
        }
    }
}
